### ISSUE TITLE
CMD+Clicking in the code editor to jump to causes delayed scrollback

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1034]
**Describe the bug**
When CMD+clicking on a component in VScode, the code editor correctly scrolls to the position in the file it's in, but then changes position. This also occurs if you manage to move the cursor to a line in the component inbetween the two steps

**Screen grab**
https://user-images.githubusercontent.com/2945037/113151186-be120380-922c-11eb-8a2b-9ea27c3d30c1.mp4

**Repro**
1. Open up https://utopia.pizza/p/a645be4c-alpine-climb/ 
2. Find a `UIContextMenuRow` in `storyboard.js`
3. CMD+Click on it
4. (optional: Click quickly into the code before it jumps back)

Observed: VSCode is undecided
Expected: VScode is assertive

**Comment by maltenuhn** [comment]
@balazsbajorics or @Rheeseyb - I think this is fixed with your changes, right?

**Comment by Rheeseyb** [comment]
Yep this was fixed!
