### ISSUE TITLE
Overwrite files message in vscode

### ISSUE THREAD

**Issue by Rheeseyb** [concrete-utopia/utopia#1041]
When reloading Utopia with a file open with unsaved changes, then making a change to that code, trying to save the code will then ask if you want to overwrite, since the file on disk is newer.

I believe this to be caused by our writing of all project files to IndexedDB when starting the vscode-bridge, implying we could maybe fix this by checking if the file written to IndexedDB is already up to date before writing.

**Comment by maltenuhn** [comment]
Is this still open?

**Comment by seanparsons** [comment]
Ah no, this is closed by #1107.
