### ISSUE TITLE
use `findMatchingTemplatePath` to try to preserve old UIDs when a model update comes from the parser

### ISSUE THREAD

**Issue by balazsbajorics** [concrete-utopia/utopia#1044]
We already have a simple heuristic / functionality in `removeNonExistingViewReferencesFromState` that uses `findMatchingTemplatePath` that tries to compare the old parsed model vs the new parsed model and it is capable of finding a matching element with changed UID. We only use this to "save" the selectedViews and highlightedViews arrays in the editor state, but we might as well use this to actually overwrite the UIDs in the updated parsed model.

This could fix a class of bugs in our spying / caching and UI where something is keyed by a UID or template path and because of the UID update we essentially have to reload the ui (leading to flashing, or showing outdated information for one frame, or loss of selection etc)

**Comment by maltenuhn** [comment]
I suppose we'll have a discussion about how we want to improve this - or did this form part of your fixes

**Comment by maltenuhn** [comment]
@balazsbajorics ^ ^

**Comment by balazsbajorics** [comment]
I think https://github.com/concrete-utopia/utopia/pull/1102 fixed this
