### ISSUE TITLE
Adding images to Utopia always shows "Assets replaced" popoup

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1074]
**Problem**
When adding an image to Utopia by e.g. adding it to the file browser, we show a toast that starts with "Assets replaced". However, this happens also when an image is added to the editor for the first time - so there is no replacing involved.

We introduced this toast to indicate that image assets that have been _replaced_ may need an editor update. However, it appears that now this toast fires always:
 
(in image-insert.ts: )
```
export function fileResultUploadAction(fileResult: FileResult, targetPath: string): EditorAction {
  switch (fileResult.type) {
    case 'IMAGE_RESULT': {
      const afterSave = EditorActions.saveImageReplace()
```

where saveImageReplace invokes
```
case 'SAVE_IMAGE_REPLACE': {
          const toastAction = showToast(
            notice(
              'Assets replaced. You may need to reload the editor to see changes.',
              'WARNING',
              true,
            ),
          )
```

**Comment by maltenuhn** [comment]
@enidemi I think this is a duplicate of #1218 - can you confirm?

**Comment by enidemi** [comment]
It is the same issue. Fixed in https://github.com/concrete-utopia/utopia/pull/1243.
