### ISSUE TITLE
Move back to the default CRA file / folder structure for the default project on pizza / .app

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1117]
**Problem**
With multifile editing now a reality, the `App` component by default should live in `app.js` and be imported into the Storyboard, so we can show that Utopia projects are just 'vanilla' react projects with an extra folder

- [ ] move `App` into `app.js`
- [ ] import it into `index.js` and render it there
- [ ] verify that the external preview works
- [ ] import `App` into the default storyboard
- [ ] render it into a scene
- [ ] Check we can make edits to it

**Comment by seanparsons** [comment]
@maltenuhn If I were to sum up the changes, the default project would look like this:

- `/src/app.js` - Contains the `App` component we currently have.
- `/utopia/storyboard.js` - Contains just the `storyboard` value with a single scene for `App`.
- `/src/index.js` - The preview code we currently have with possibly a tweak to the import.

**Comment by maltenuhn** [comment]
@seanparsons that all looks right, and should be exhaustive (since package.json is already correct AFAIK, and we don't include a `styles.css` file we'd need to import.
