### ISSUE TITLE
Reparenting files via the file navigator isn't working anymore

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1147]
**Problem**
Trying to reparent code files in the file navigator appears broken

**Repro**
1. Grab `storyboard.js` and try to move it from the `utopia` folder to the `src` folder.

Observed: no drop target highlights, dropping it on `src` doesn't do anything

Expected: drop target highlights work, and dropping it results in a reparent.

NB we seem to have the same problem for file uploads, something about our favourite D&D library is flaky here

**Comment by enidemi** [comment]
Drag and drop issues in this card:
- it is possible to drag folder into child folder
- drop target can only be directory, on files nearest ancestor folder should be shown
- uploaded assets should be shown with an extra tag after the filename (this was already there long ago)
```<span style={{ border: '1px solid primary', padding: 2, fontSize 9, color: primary }}>S3</span>```
