### ISSUE TITLE
Pragma and missing jsx import result in silent failures

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1156]
**Problem**
- [ ] if the user forgets to add `import { jsx } from 'utopia-api'` there are no elements on the canvas and we show no error message
- [ ] kill the pragma, check what still breaks 🔥
- [ ] if there’s a pragma but no imported jsx, we shouldn’t fail silently
- [ ] check that we can still use emotion with a pragma, this notwithstanding

**Comment by enidemi** [comment]
I put this back to TODO, because now I always see the runtime error screen correctly.
