### ISSUE TITLE
Selection from code to canvas isn't updating

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1159]
**Problem**
Moving the cursor in code does not select the element on the canvas. Video below.

Specific STR a bit unclear, but involved insertion, modifying css in code incl deleting and re-adding and undoing / redoing changes, and then navigating via arrow keys and mouse. 

https://user-images.githubusercontent.com/2945037/116136008-b4fc4100-a6c9-11eb-992c-5c37dcb79a40.mp4

**Comment by Rheeseyb** [comment]
This _might_ be related to #1128
