### ISSUE TITLE
Missing Emotion error / Instead get Utopia Error: ScenePath is not provided for Card

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1171]
Here's another (broken) project. It should fail because the styledComponent is using a component that's defined after it is declared in the file. 

Codesandbox [here](https://codesandbox.io/s/suspicious-tharp-i209p?file=/src/App.js) shows:
```
You are trying to create a styled element with an undefined component.
You may have forgotten to import it.
```

Utopia [here](https://utopia.pizza/p/5df4e6cd-successful-plain/) instead shows:
```
Error: Utopia Error: ScenePath is not provided for Card
```

**Comment by balazsbajorics** [comment]
the linked utopia project contains another nice new bug: it fails to load because of a duplicate UID issue. the original behavior was to auto-fix uid issues but I think the recent changes moving the validation to multi-file broke that behavior . I'm gonna make this a separate ticket because it leads to perceived data loss by the user!!!

**Comment by maltenuhn** [comment]
The sample project still won't load for me. I'm getting a "No File Open" message
![image](https://user-images.githubusercontent.com/2945037/118108344-cb97dd00-b3d7-11eb-8322-e38972a8fdb3.png)

When I click on the left menu, I get
![image](https://user-images.githubusercontent.com/2945037/118108398-dbafbc80-b3d7-11eb-92cb-5b4ae616550d.png)

Should I log a new ticket for this @balazsbajorics  ?

**Comment by balazsbajorics** [comment]
Here's a reproduction project:

https://utopia.pizza/p/4d33c60f-successful-plain/

and the same in codesandbox with the "proper" error message: https://codesandbox.io/s/gracious-lovelace-nr0in?file=/src/card.js

**Comment by balazsbajorics** [comment]
@maltenuhn this bug hits a Utopia shortcoming: we are not evaluating the real js file in a single pass, instead we slice it up to chunks of "arbitrary js" (which we eventually evaluate) and "parsed" parts (which we **never** evaluate, instead we essentially simulate what would React do when evaluating it). The ui-jsx-canvas code spaghetti then takes these arbitrary parts, and the parsed parts, and tries to create a frankenstein's javascript monster which more or less looks like what the original file would produce. the goal of course is to match native javascript 100% both visually and react-behaviorally.

I can see two options to mitigate/solve this problem:
1. the quick, dirty and easy way out is that we can use eslint's `no-use-before-define` rule and make it an Error – this would let us produce _an_ error on the canvas, if not the exact same runtime error as codesandbox has
2. the hard way would be to dig into ui-jsx-canvas and figure out how to interleave the arbitrary and parsed parts in a way that when we are evaluating the arbitraries, they would properly break on things like this use-before-define situation. the upside is that this would be bringing the evaluation closer to JS.

**Comment by balazsbajorics** [comment]
> 2. the hard way would be to dig into ui-jsx-canvas and figure out how to interleave the arbitrary and parsed parts in a way that when we are evaluating the arbitraries, they would properly break on things like this use-before-define situation. the upside is that this would be bringing the evaluation closer to JS.

I would insert that the biggest risk with Option 2 is how much potential regressions this could make – this code base is the heart of how the canvas works and both the multifile project and the modern-syntax-scenes project showed us that there's no way to touch these parts without causing bugs that are hard to track down and all over the place

**Comment by maltenuhn** [comment]
Uh oh. Yeah, (1) seems like the best option here...

**Comment by balazsbajorics** [comment]
oh hum fun fact, the linter was triggered by Monaco Wrapper and we never set up the trigger with VSCode…
I might as well bring back the errors tab while fixing this...
