### ISSUE TITLE
Missing error for this sample project (glistening-apocalypse)

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1175]
**Describe the bug**
The incorrect code doesn't produce an error on the canvas, or red squiggly underlines in the code editor.

STR:
- open https://utopia.pizza/p/ad0597ba-glistening-apocalypse/
- check the console and line 29 of app.js for the surplus `'`
- behold the canvas, which does not show an error

![image](https://user-images.githubusercontent.com/2945037/116558675-98455080-a8f7-11eb-9096-7fe1e827bcf4.png)

Console:
![image](https://user-images.githubusercontent.com/2945037/116560769-9b414080-a8f9-11eb-8355-8cd2d4a0c9e1.png)

**Comment by seanparsons** [comment]
@maltenuhn This is showing an error for me...

**Comment by maltenuhn** [comment]
@seanparsons that's bizarre, I took the screenshot 3h ago. Is it possible something we merged meanwhile would have fixed this?

**Comment by maltenuhn** [comment]
@seanparsons never mind, I can reproduce it. Open the project, _delete_ the single quotation mark, _add it_ (VSCode probably will insert two), and then delete one. Result:

![image](https://user-images.githubusercontent.com/2945037/116584231-0d705000-a90f-11eb-8bde-8a76ccad67c8.png)
