### ISSUE TITLE
Performance: rewrite getJSXComponentsAndImportsForPathInnerComponentFromState 

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1185]
**Problem**
Rewrite `getJSXComponentsAndImportsForPathInnerComponentFromState` and `getJSXComponentsAndImportsForPathInnerComponent` as they're leaning on the resolve function but are called for each navigator item for example.The latter does some collation of components which I'm a little dubious of looking at it now as well.

**Comment by seanparsons** [comment]
Function has been eliminated already.
