### ISSUE TITLE
Missing error for missing end tag of a render function

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1193]
Sample project: https://utopia.pizza/p/2da66dec-diligent-sink/

Error is on line 11 or 12 (missing closing `</div>`), but canvas shows no obvious error

**Comment by balazsbajorics** [comment]
I have a feeling that merging #1182 fixed this. I can't reproduce the problem, it shows a nice error message for me.

<img width="2083" alt="image" src="https://user-images.githubusercontent.com/2226774/117129463-fdd58900-ad9e-11eb-9866-0525fbba45cc.png">

**Comment by maltenuhn** [comment]
So it seems! Thanks @seanparsons  :)
