### ISSUE TITLE
Logging out in one tab shows "Utopia is offline" error bar

### ISSUE THREAD

**Issue by Rheeseyb** [concrete-utopia/utopia#1196]
STR:

1. Open a project in one tab, log in, and open the Chrome inspector
2. Open another tab and go to `/logout`

The open project will now display the "Utopia is offline" status bar along the top, and will repeatedly make failing (with a 401 status) calls to the server.

MN edit: see also #1196

**Comment by maltenuhn** [comment]
@Rheeseyb , meet @balazsbajorics who I understand has pretended to have similar interests!

**Comment by balazsbajorics** [comment]
hello rheese

**Comment by Rheeseyb** [comment]
Yeah I've already tested against #1194 and it's still an issue there. I'd say this issue should be tackled separately after that fix has been merged

**Comment by balazsbajorics** [comment]
I'm extending that PR, sorry for opening it a bit prematurely. I'll ping you once I'm done there!

**Comment by balazsbajorics** [comment]
so after my PR, the user sees a bit more information about what is up. I did not kill the Utopia is Offline message, so it shows two error bars right now. In my local testing, as soon as I logged back in, both error status bars went away and peace returned. the pr is merged, the new editor will be deployed soon and we can give it a stress test!
