### ISSUE TITLE
Create a self-closing "log me in" page for re-authentication

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1209]
**Problem**
Today logging in navigates you away from the project you're currently viewing / working on / considering forking. That's not great because a) we stop you from navigating away if the project isn't saved (but you don't know at that point that we will actually save it!),
b) there's always the potential for actual data loss, and c) it's kind of an antipattern in editors

**Solution**
- [x] Create a self-closing "log me in" page for re-authentication
- [x] Open that up in a new window (ideally) or tab
- [ ] Use that pattern in the places where we have log in from within the editor today, particularly the "You're not signed up" bar atop the editor.

**Comment by seanparsons** [comment]
@maltenuhn If the user has multiple tabs open should all of them trigger their forking/etc behaviour after successfully logging in?

**Comment by maltenuhn** [comment]
@seanparsons I think so - which tab you "triggered" the log in from shouldn't make a difference IMO. If we find that the resulting behaviour is too aggressive, we should fix the behaviour. Does that sound right to you?

**Comment by seanparsons** [comment]
@maltenuhn Yeah, it has implications for how it's implemented I believe so I thought it best to check upfront.

**Comment by maltenuhn** [comment]
Thanks @seanparsons ! @balazsbajorics as you've been touching the Autofork / semiautofork code - anything to add here?

**Comment by balazsbajorics** [comment]
> Thanks @seanparsons ! @balazsbajorics as you've been touching the Autofork / semiautofork code - anything to add here?

nope, that was orthogonal IMO, as I was just tweaking the "should auto save" logic
