### ISSUE TITLE
Hook up the "You're logged out, this isn't your project, you can fork it" and "You're logged in, this isn't your project, so sign up to save it" panels

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1210]
**Problem**
When you're viewing a project that isn't yours, or you're not logged in, we don't really give you a way to understand this (and, then, an affordance for signing in or forking)

**Solution**
There's a branch that contains two panels and a button: https://github.com/concrete-utopia/utopia/tree/feature/fork-and-login-panels
- Panel A **This isn't your project, you are not signed in** panel with the ability to fork it
- Panel B  **This is a new project, you are not signed in** panel with a clear CTA to sign in / up / on to save your work

The following functionality needs to be wired up
- [ ] Show Panel A in all left menus at the bottom, if the condition is met
- [ ] Show Panel B in all left menus at the top, if the condition is met
- [ ] Ensure that there's only max 1 of these visible
- [ ] Wire in the "Sign in" logic, ideally using the new modal window
- [ ] Wire in the "Fork it" logic
- [ ] Review / wire in the project name / description / author pieces of data
- [ ] Review the copy / designs, and point out anything that could be improved : )

**Comment by seanparsons** [comment]
Should this still have the blocked label on it @maltenuhn?
