### ISSUE TITLE
VSCode "replays" highlight / selection changes with a delay if performance is bad

### ISSUE THREAD

**Issue by balazsbajorics** [concrete-utopia/utopia#1253]
In situations when the editor slows down, if you click around to change the selection, you can see VSCode "replaying" your selection changes with a delay, instead of skipping to the last selected/highlighted element.

I think this is worst on Dev mode and slow computers, but it is pretty annoying nonetheless

**Comment by seanparsons** [comment]
Context taken from conversation about this:
- The selection changes are being pushed down through the mailbox as fast as they happen.
- Conceivably we could have it skip updates of this kind if there are later ones on the VS Code side in the same batch of messages.

**Comment by Rheeseyb** [comment]
I highly suspect that this is down to the extension processing the mailbox in order, so if there are a bunch of highlight messages pending it will just process them in order
