### ISSUE TITLE
Typing a character into div contents causes inspector to re-render even though selection hasn't changed

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1262]
**STR**
1. New project
2. Type "Hello world" into the div in <App>, one character at a time

Observed: on each keystroke, inspector re-renders and flickers (maybe a section is being added?).
Expected: it doesn't, since selection doesn't change

NB This seems like a pretty recent (1w or less) regression

**Comment by maltenuhn** [comment]
@enidemi could this be related to #1264 ?

**Comment by enidemi** [comment]
This looks like a different problem, that flickering is very annoying

**Comment by maltenuhn** [comment]
Oh well - at least the flickering is new, hopefully that'll help track it down faster
