### ISSUE TITLE
Project fails to load, crashes on left menu

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1269]
**Problem**
This project https://utopia.pizza/p/5df4e6cd-successful-plain/ won't load for me. I'm getting a "No File Open" message
![image](https://user-images.githubusercontent.com/2945037/118108344-cb97dd00-b3d7-11eb-8322-e38972a8fdb3.png)

When I click on the left menu, I get
![image](https://user-images.githubusercontent.com/2945037/118108398-dbafbc80-b3d7-11eb-92cb-5b4ae616550d.png)

_Originally posted by @maltenuhn in https://github.com/concrete-utopia/utopia/issues/1171#issuecomment-840445452_

**Comment by Rheeseyb** [comment]
Looks like we have some overly aggressive UID duplication protection (in this case triggered by what looks like a copy paste of code with a hand-rolled UID). The throw is here: https://github.com/concrete-utopia/utopia/blob/master/editor/src/core/model/element-template-utils.ts#L71, so either that should be removed or handled.

**Comment by balazsbajorics** [comment]
I have an unfinished PR that should solve this problem but I gave up after not being able to make it work for a day. I think I should pick it up with fresh brain and look at it again

**Comment by maltenuhn** [comment]
#1192 was merged in the end, so closing this
