### ISSUE TITLE
Unable to delete a View on the canvas

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1276]
**Problem*

Selecting and deleting a view on the canvas fails. Nothing obvious in the console, doesn't seem to be a cursor-focus issue since no code gets deleted

**Video**

https://user-images.githubusercontent.com/2945037/118661527-17d38a80-b7e7-11eb-9325-5953272af993.mp4

https://utopia.app/p/51345c80-immovable-object/

**Comment by seanparsons** [comment]
@maltenuhn I don't _seem_ to be able to reproduce this and that view isn't even in the linked project for some reason.

**Comment by maltenuhn** [comment]
@seanparsons Me neither, it probably ~fixed itself~ was fixed by one of the many selection or UUID-related points. Fingers crossed for that at least!
