### ISSUE TITLE
Making a change via the formula bar updates the code, but not the canvas

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1293]
**Problem**
Making changes to the code via the formula bar (see video) and sometimes the inspector fails, without an obvious problem in the console. See video here, with Redux devtools open. 

(redux devtools export available here https://www.dropbox.com/s/6xcjes9a0pz60jf/canvas%20not%20updating%20json.txt?dl=0
)

https://user-images.githubusercontent.com/2945037/119233738-51c3ca00-bb22-11eb-954d-72e198105c2e.mp4

**Comment by seanparsons** [comment]
@maltenuhn Do you have the code for this project to hand?

**Comment by maltenuhn** [comment]
@seanparsons unfortunately not, but I was able to replicate it pretty easily in new projects. It's possible that the merged PRs might have fixed this though, but until the code editor is live on pizza I can't verify that for sure.

**Comment by seanparsons** [comment]
@maltenuhn Does it only reproduce reliably while making changes to direct children of the `Scene` component by any chance?

**Comment by maltenuhn** [comment]
@seanparsons I believe so. AFK so can't speak *with certainty* to the "only" part - but that is what I was doing here.
