### ISSUE TITLE
Use selection-independent target path in layout section (follow up from #1278)

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1297]
AFAIK the rest of the inspector uses a target path property that is independent of selection – we could use that here too, or at least put a comment here noting the divergence!

_Originally posted by @balazsbajorics in https://github.com/concrete-utopia/utopia/pull/1278#discussion_r635834688_

Notes MN: I've kept the branch `fix/inspector-layoutsection-cleanup` open

**Comment by seanparsons** [comment]
Closing after talking to @balazsbajorics about this issue.
