### ISSUE TITLE
Element on canvas gets deselected after making a css change

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1299]
**To Reproduce**
Steps to reproduce the behavior. For canvas tasks, take care to note down all relevant key holds, keys typed, selected state etc. E.g:

1. Open a new project
2. Use the inspector to make changes to the style object of `View`
3. Use the code editor to delete a line of CSS

Expected: `View` stays selected
Observed: `View` loses selection

**Hard Evidence**
- Redux devtools exported states: https://www.dropbox.com/s/xjhwo76ve11wz3g/element-still-gets-deselected-after-style-edit.json?dl=0
- CCTV footage: 
https://user-images.githubusercontent.com/2945037/119374538-992c9080-bcb1-11eb-92fc-7fac0cd3b00f.mp4
- Test project: https://utopia.pizza/p/1489e5e4-honeysuckle-whip/

**Comment by maltenuhn** [comment]
Was the devtools export here at all helpful?

**Comment by seanparsons** [comment]
This is fixed by #1308.
