### ISSUE TITLE
component becomes uneditable after making a css change

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1304]
**STR**
1. New project
2. Click into `<App>` and select the div
3. Change its opacity via the inspector
4. Change its opacity to an equation via the code editor (e.g. `opacity: .5 + .2` )

Observed: The div becomes deselected, you can no longer enter / edit the component itself
Expected: remains selected, remains editable

Video: 
https://user-images.githubusercontent.com/2945037/119543337-7620e000-bd88-11eb-8f00-189c419e8887.mp4

Redux devtools json export: https://www.dropbox.com/s/ha1311jbjqizj9p/element-deselected-uneditable-after-css-change.json?dl=1

**Comment by seanparsons** [comment]
@maltenuhn I think this bug has the video for #1299.

**Comment by maltenuhn** [comment]
@seanparsons Oops, so it does. Here's the one I'd meant to upload!

https://user-images.githubusercontent.com/2945037/119812205-d0808480-bedf-11eb-819d-31a0b5dae54e.mp4

**Comment by maltenuhn** [comment]
(However, I'm unable to reproduce this right now on pizza - not sure if it's fixed by something merged yesterday, or I hit a specific failure mode not in the repro steps)
