### ISSUE TITLE
Deleting `card.js` from the filebrowser doesn't update the canvas.

### ISSUE THREAD

**Issue by enidemi** [concrete-utopia/utopia#1315]
After deleting the file the canvas still renders the `Card` component.
Inserting new components/divs from the insertmenu to the parent `App` still keeps the Card on the canvas. The insertmenu correctly doesn't show the Card, because it was deleted.

How it should work: there is an error on the canvas when using a non-existing component.

After reloading the correct error shows up.

<img width="1094" alt="Screenshot 2021-05-28 at 14 19 49" src="https://user-images.githubusercontent.com/4403069/119983145-10b73400-bfc0-11eb-8365-5a5af9a598d5.png">

**Comment by maltenuhn** [comment]
I've just reproduced this on pizza. (Both removing the `import { Card } from `/src/card.js` and removing the `export const Card = ... ` now are working correctly, but _deleting_ card.js via the file browser still causes this problem)

**Comment by enidemi** [comment]
Fixed by https://github.com/concrete-utopia/utopia/pull/1335
