### ISSUE TITLE
changing the name of an import file doesn't update the canvas if there's an error

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1330]
**STR**
1. create a new file
2. export out a component
3. import it into app, but type the wrong filename in the import statement
4. (canvas should error)
5. fix it, save the file

Expected: it's fixed
Observed: error message stays, and refers to the previous file

<img width="1402" alt="Screenshot 2021-06-02 at 20 54 04" src="https://user-images.githubusercontent.com/2945037/120544011-dba64980-c3e4-11eb-9a2e-cf9a1aa81f50.png">

**Comment by seanparsons** [comment]
I have been completely unable to reproduce this, even to the extent of finding a different but related issue: #1334

**Comment by seanparsons** [comment]
@maltenuhn Are you still able to reproduce this? I'm wondering if some other issue happened prior to this which is the actual cause.

**Comment by maltenuhn** [comment]
@seanparsons I just tried it, and now am also unable to reproduce it. I suspect / hope that some of the many fixes around linting / error handling / better error messages fixed it!

**Comment by seanparsons** [comment]
Sounds good to me!
