### ISSUE TITLE
Recoil context not available in this sample project

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1332]
**Problem**
Trying to replicate this Todo List project https://codesandbox.io/s/goofy-tree-gb5j6?file=/src/index.js:234-251 in Utopia, it's not clear how to use the <RecoilRoot  /> component.

The original project places it into `index.js` - which I guess will fail in our case, since the canvas disregards it. However, putting it into `App.js` also fails:

![image](https://user-images.githubusercontent.com/2945037/120545257-5459d580-c3e6-11eb-91f4-cc337986f1ba.png)

https://utopia.pizza/p/9adb578b-todo-app/

**Comment by enidemi** [comment]
The fixed version is https://utopia.pizza/p/37fba76f-todo-app/ with the RecoilRoot moved to wrap the Scene component.

What we need here is better error messages, and better error messages for the runtime code in general.

**Comment by maltenuhn** [comment]
Thanks @enidemi! 
1 - how should we handle the error message here?
2 - do you know why the navigator in your (fixed) project is only showing the first item? 

<img width="1436" alt="Screenshot 2021-06-03 at 21 04 15" src="https://user-images.githubusercontent.com/2945037/120705426-b7fc0580-c4af-11eb-9461-8c78812f3fca.png">

**Comment by balazsbajorics** [comment]
I take over the error message part – Eni's stack traces which she shared with me had some indication that we have a chance of including source maps to ever more places – I'll try to do that!

**Comment by Rheeseyb** [comment]
After a bit of investigating, It appears there are now 3 remaining problems with this project, so I'm going to break this up into 3 tickets as follows:

1. Missing source link in the "This component must be used inside a <RecoilRoot> component" error
2. The text child of `<option>` elements becomes garbage when running in the canvas
3. React Suspense isn't supported on the canvas

I'll then close this ticket and reference those.

**Comment by Rheeseyb** [comment]
Closing as this is now replaced by:

1. #1415 
2. #1414 
3. #1416
