### ISSUE TITLE
Support fragments in the navigator / on the canvas in the inspector

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1340]
**STR**
1. Open  https://utopia.pizza/p/37fba76f-todo-app/ 
2. Observe how the first child of App is sometimes showing up in the navigator, and nothing is selectable on the canvas
3. Replace the fragment `<>` in `App`  with a div

Now the navigator populates. But because the original creator of this example chose a coding style where almost _everything_ is a fragment, you still can't select things via the canvas, _and_ the inspector is not letting you modify them if you select them via the navigator.

<img width="1436" alt="Screenshot 2021-06-03 at 21 04 15" src="https://user-images.githubusercontent.com/2945037/120705426-b7fc0580-c4af-11eb-9461-8c78812f3fca.png">

_Originally posted by @maltenuhn in https://github.com/concrete-utopia/utopia/issues/1332#issuecomment-854144981_

**Comment by enidemi** [comment]
We supported fragments in the past, I think it is not covered by tests well enough.
