### ISSUE TITLE
We don't treat /public folder as a root directory in the canvas

### ISSUE THREAD

**Issue by Rheeseyb** [concrete-utopia/utopia#1344]
Adding an asset to the `/public` folder should make it directly accessible on the root domain, but currently to reference assets there we have to give the asset path including the `/public` prefix.

Example project here: https://utopia.app/p/7f0c1fb1-public-assets/ - the second `img` tag in `app.js` should render correctly.

**Comment by seanparsons** [comment]
@Rheeseyb Does this mean that only `/public` is treated as a root under the project URL? Or something like `/public` and then `/`?

**Comment by Rheeseyb** [comment]
> @Rheeseyb Does this mean that only `/public` is treated as a root under the project URL? Or something like `/public` and then `/`?

I'd say the latter, so if something doesn't exist under `/public` we fall back to trying `/`
