### ISSUE TITLE
Would be beneficial if the asset loading handled the appropriate ETag headers.

### ISSUE THREAD

**Issue by seanparsons** [concrete-utopia/utopia#1350]
Currently if an asset is loaded via a URL like `http://utopia.app/p/aabbcc/image.png` those are loaded via S3 every time they are requested.

It would be beneficial for the Etag headers to be returned as part of the response along with the service handling them in the request to return a 304, which would save on bandwidth going back and forth.

**Comment by maltenuhn** [comment]
This is a nice find!
