### ISSUE TITLE
Figure out why / how font importing isn't working

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1370]
**Problem**
Open  https://codesandbox.io/s/optimistic-sun-x5k03?file=/src/styles.css - see how the import suceeds, and the first line is styled differently

compare to https://utopia.app/p/ec77ab7c-lyrical-candle/ - import fails.

Three potential root causes I can think of:
* I renamed the font file via file navigator after uploading it
* Something about the paths for imports isn't working / correct, maybe because the import is in a CSS file
* something about importing the CSS file

Given that I had to use `import '../public/styles.css'` it seems like there's also an inconsistency between us and CRA more generally.

**Comment by Rheeseyb** [comment]
Caused by an issue with parsing a project that contains an asset file, which is required when serving individual files from that project. Fix is incoming

**Comment by seanparsons** [comment]
Fixed by https://github.com/concrete-utopia/utopia/pull/1375
