### ISSUE TITLE
add some sort of interaction to the navigator to be able to focus on a component

### ISSUE THREAD

**Issue by balazsbajorics** [concrete-utopia/utopia#1396]
right now, you have to use the context menu to Edit component in the navigator, it feels hard to discover and flow-stopping. We should either show a "closed chevron" or some other button to activate Focus mode. I personally wouldn't mind if double clicking in the navigator would mirror double clicking on the canvas! (instead of activating the rename mode, which can be activated from CMD + R anyways)

**Comment by Rheeseyb** [comment]
Double-click to focus a component was added a while back
