### ISSUE TITLE
Colour picker scrubbing makes changes arrive twenty seconds later in the code editor

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1408]
With the VSCode changes, we have a pretty knarly performance regression that seems to affect some scrubbable controls:

STR:
- new project
- select innermost div
- use the background fill selector from the inspector
- scrub any of the controls inside the colour picker. Stop, slide again.

Observed: queues up updates to the code editor that can arrive up to twenty seconds later.
Expected: shouldn't : ) 

NB: this does work "as expected" with opacity - canvas updates real-time, code updates at end of scrub. List of things to check:

- [x] `number-control` with scrubbable label
- [x] `slider control` (seems fine, maybe optimisations only exist for opacity?)
- [x] all scrubbable controls in the colour picker
- [x] all scrubbable controls in the gradient selector, including the gradient stops

**Comment by Rheeseyb** [comment]
Closed by #1409 and #1410
