### ISSUE TITLE
The preview is no longer previewing anything for this project

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1421]
**STR**
Open https://utopia.app/p/21aba8be-pastoral-reading/ and compare canvas with preview (CMD+P)

Update: per @balazsbajorics voluntary confession, this resulted as a byproduct of introducing Next

<img width="1439" alt="Screenshot 2021-06-23 at 10 21 40" src="https://user-images.githubusercontent.com/2945037/123071719-d00ad900-d40c-11eb-9290-889b21a98940.png">

**Comment by seanparsons** [comment]
While I was testing this, it seemingly stopped happening which is worth keeping an eye on as I never definitively nailed down what was going on.

**Comment by balazsbajorics** [comment]
I would add that I was talking about the `/preview/<id>`, and this is the `/share/<id>` url so it was _not_ the next.js change

**Comment by Rheeseyb** [comment]
Hmmmm :thinking:
