### ISSUE TITLE
Creating a new file leaves the file name edit field focused

### ISSUE THREAD

**Issue by Rheeseyb** [concrete-utopia/utopia#1425]
**Describe the bug**
When creating a new file via the file browser, after creating the file, giving it a name, and then hitting enter, a new row appears in the file browser with the file name in a focused and editing state.

**To Reproduce**
1. Open the file browser
2. Click the "Add Code File" button that appears when highlighting the "src" folder
3. Give the new file a name and hit enter

Result: The newly created row is focused and in an editing state

**Expected behaviour**
The newly created row should be selected but not in an editing state

![file_insert_name_bug](https://user-images.githubusercontent.com/1044774/123168975-9ec3f480-d470-11eb-9dde-e9b99d9c68b8.gif)

**Comment by jatinsandilya** [comment]
@Rheeseyb I'd like to take this up! ✋🏼

**Comment by balazsbajorics** [comment]
awesome! I'm excited to tell you that you might become our second contributor!

here's some pointers about the issue: the file browser items are rendered here https://github.com/concrete-utopia/utopia/blob/1e69b53a2d1b55eadc31e50f1f067c708d71ef2f/editor/src/components/filebrowser/fileitem.tsx#L213
(sorry, it's an old-style class component, we probably wrote it before Hooks came out...)

there's two keyDown handlers in this class: [`onKeyDownFilename`]( https://github.com/concrete-utopia/utopia/blob/1e69b53a2d1b55eadc31e50f1f067c708d71ef2f/editor/src/components/filebrowser/fileitem.tsx#L282) and [`inputLabelKeyDown`](https://github.com/concrete-utopia/utopia/blob/1e69b53a2d1b55eadc31e50f1f067c708d71ef2f/editor/src/components/filebrowser/fileitem.tsx#L563)

if I were you, this is where I'd start digging! my hunch is that when you press enter to insert file, the same Enter also starts a new rename inside `onKeyDownFilename`
