### ISSUE TITLE
"Unexpected model for ResourceEditorInput" error in this project

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1448]
**Problem**
Opening this project from my account leads to two "unable to open" errors:
https://utopia.app/p/77aab5d6-peach-atlasaurus/

![image](https://user-images.githubusercontent.com/2945037/124031795-a8f56e00-d9ef-11eb-87aa-677bb7424107.png)
(also, note the uncaught syntax error here. Related?)

![image](https://user-images.githubusercontent.com/2945037/124031755-9e3ad900-d9ef-11eb-9a18-b5e913b42411.png)

**Comment by seanparsons** [comment]
@maltenuhn Was there any particular trigger for this? It looks like VS Code has some local data which is somehow broken, as the project loads for me and this is an error from deep within VS Code itself.

**Comment by maltenuhn** [comment]
No trigger - I just opened the project from my `/projects` page

**Comment by seanparsons** [comment]
I vote for closing this for now and if it comes up again hopefully we can determine what is triggering it as this is particularly difficult to even diagnose given it's deep within VS Code.
