### ISSUE TITLE
Speedrun "Insert ... " feature

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1455]
**Problem**
Insertion today requires you to draw-to-insert. That's tricky for a bunch of reasons tied to our canvas controls. 

**Solution**
Similar to #1453, expose a menu with the same content, and insert the component. We _might_ want a toggle to add content (so you don't end up inserting 0x0 things)

**Comment by balazsbajorics** [comment]
from Malte: "images should apply a default src IMO", we could pick some small image to be the placeholder
