### ISSUE TITLE
Resizing the code editor pane sometimes scrolls the entire editor. Only reloading fixes it.

### ISSUE THREAD

**Issue by Rheeseyb** [concrete-utopia/utopia#1469]
This one is very hard to reproduce. Sometimes dragging the split pane (from between the code editor and the canvas) to resize the code editor will trigger a scroll on the entire editor in a way that doesn't appear to be fixable. Whenever this has happened to me I've had to reload the editor. It might be a layout issue as opposed to scrolling?

**Comment by balazsbajorics** [comment]
next time it reproduces for anyone, please try to go into the chrome inspector and try to find which root element is the one that scrolled away. even if we can't prevent this from happening, we can write some hacky fix code that sets the position of root divs to 0,0 every 5 seconds or so :D

**Comment by Rheeseyb** [comment]
Succeeded by #1483
