### ISSUE TITLE
A captured props spread that is then spread into an element is never applied

### ISSUE THREAD

**Issue by Rheeseyb** [concrete-utopia/utopia#1515]
There is a problem with our project parsing, in that the following example component won't correctly apply the spread result:

```
var Card = ({ ...props }) => {
  return <div {...props}>Hello</div>
}
```

**Comment by balazsbajorics** [comment]
even this code is throwing off the canvas renderer, even though I think this was fixed a month ago in https://github.com/concrete-utopia/utopia/pull/1411

```javascript
export const FlexRow = (props) => {
  return (
    <div
      {...props}
      style={{
        position: 'relative',
        display: 'flex',
        flexDirection: 'row',
        ...props.style,
      }}
    >
      {props.children}
    </div>
  )
}
```

repro project https://utopia.pizza/p/38ffa8d6-broken-flexcol/
