### ISSUE TITLE
I can't delete elements that contain an expression (but nothing else)

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1530]
STR

1. New project, new component with prop `username`, return <span>{props.username}</span> or <span style={{ backgroundColor: props.username === 'malte' ? 'grue' : 'mauve' }} </span>
2. Render component onto new scene
3. Select the span containing username
4. Delete it

Result: cannot
Expected: can, info toast telling you "The element you deleted contained an expression".

**Comment by Rheeseyb** [comment]
Reading this issue, it sounds like you're trying to delete the root element of the component? Is that right? If so, that's something we don't support yet, because we haven't come to a conclusion of what deleting the root element should actually do to the component.

**Comment by maltenuhn** [comment]
Sorry, the STR missed an outer div - i.e. this ticket is for _anything but_ root elements.

**Comment by Rheeseyb** [comment]
I've just tried with the following
```
import * as React from 'react'
export var App = (props) => {
  const b = 'light-blue'
  return (
    <div>
      <span style={{ backgroundColor: b }}>Some text</span>
    </div>
  )
}
```

I'm able to select and delete the span from the canvas (with the editor in "edit" mode), which makes me think this is the same issue as #1558, i.e. that the deletion did nothing because it's blocked in "select" mode, so maybe we shouldn't block it.

**Comment by maltenuhn** [comment]
@Rheeseyb OMG I think that's it. Yes, I think we can allow this in select mode np
