### ISSUE TITLE
Explore resurrecting the canvas prototype for flex context on-canvas target insertion + popup menu

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1548]
experiments/insertion-plus-button-1

**Comment by balazsbajorics** [comment]
but instead of inserting an empty 50x50 div, the plus button should trigger the floating insert menu

**Comment by balazsbajorics** [comment]
I just realized there's some complexity: we need to be able to give a desired "child index" to the floating insert menu so that it inserts the child where the plus button was clicked, and not as last element
