### ISSUE TITLE
Bug: cannot delete `Card` in local default project

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1558]
STR
1. New project on localhost
2. CMD+click to select Card
3. Use backspace to delete it

expected: can delete
Observed: cannot. 
Twist: after moving it, or possibly after inserting a child into it, can delete it

**Comment by Rheeseyb** [comment]
I think this is because Select mode doesn't enable deletion from the navigator or canvas - that functionality is locked behind edit mode. Seems like is shouldn't be?
