### ISSUE TITLE
The navigator is out of sync with the project

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1559]
STR
in the default project, convert the div to a flex layout.
The navigator shows it not as a flex layout
Convert it back
navigator now shows it
why

<img width="1095" alt="Screenshot 2021-07-21 at 21 14 26" src="https://user-images.githubusercontent.com/2945037/126554178-b40b4d11-0e34-4505-9866-b7b616004567.png">

**Comment by balazsbajorics** [comment]
how do you "Convert it back"?

**Comment by maltenuhn** [comment]
click on 'pins' in layout system. Or use undo, I can repro with either

**Comment by balazsbajorics** [comment]
does reproduce with cmd + z to undo

**Comment by Rheeseyb** [comment]
This appears to be a duplicate issue that was fixed a while back by #1628
