### ISSUE TITLE
Improve the search / filtering for the classname control

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1565]
**Problem**
The search pattern for React Select misses some patterns we feel it "should" catch

1. > "roun-lg - I expected that to autocomplete to rounded-lg"

(Everything below removed as mentioned in the comment, because they have already been addressed using very similar solutions)
~2. we pollute the results with unrequired hover / focus pseudoclasses~
~3. we pollute the results with unrequired sized results (`sm:` . . )~

~**Solution Ideas**~
~Not sure if these will help at all :)~

~1. Remove size-modified results from search results unless we have an exact match for the modifier with a whitespace before or after, or start of string with colon. We'll get some false positives for e.g. `shadow-lg` (i.e. `shadow-lg` _and_ `lg:shadow-sm` but I think those become edge cases.
2. only include the pseudo class results  (hover, focus, etc) in the search set if we have a  partial (3 letters+ match on one of them explicitly). Because of ambiguity (`focus` can be a partial match~

**Comment by Rheeseyb** [comment]
2 and 3 are already solved by #1554 using tactics very similar to those mentioned. The only part that needs addressing is 1, so I'll update the ticket

**Comment by Rheeseyb** [comment]
For number 1 I believe we should just string split on any form of punctuation
