### ISSUE TITLE
🐛 TW: I sometimes had trouble entering the input field via the mouse. Changing selection would fix it.

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1599]
**Problem**
Sometimes (not exactly clear on when) it wasn't possible to enter the input. Deleting a classname would fix this. 

Suspected conditions: 
1 - making a canvas or inspector change before
2 - _not_ making one before
3 - having added a classname, using escape to exit out, trying to add another one

**Comment by Rheeseyb** [comment]
I've been trying to repro this and the _only_ way I can is by selecting multiple elements (which disables the input). The styling needs changing for that, but I'm not sure that's the issue you've been hitting against here.

Where were you clicking when this happened to you? Did you only have one element selected or multiple?

**Comment by Rheeseyb** [comment]
I have opened #1607 to tackle the issue mentioned in my comment.

**Comment by Rheeseyb** [comment]
Closing as I believe this has been fixed, but will re-open if someone hits this problem again
