### ISSUE TITLE
Resurrect the "Interactive Resize Controls" experiment

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1603]
@enidemi do you have the link to this one? Was it just one PR?

**Comment by enidemi** [comment]
This was the original experiment: https://github.com/concrete-utopia/utopia/pull/530

This second version extends it to flex grow/shrink properties and also adds some other UI elements that as I remember were not useful https://github.com/concrete-utopia/utopia/pull/540 . 

I think it's enough to use the first one.
