### ISSUE TITLE
Adding style via code didn’t update layout section of the inspector, but then saving and updating them did

### ISSUE THREAD

**Issue by seanparsons** [concrete-utopia/utopia#1645]

**Comment by Rheeseyb** [comment]
Something appears to be out of sync when using [this project](https://utopia.pizza/p/7a443ee3-ubiquitous-barnacle/), clicking immediately after the `0` in `opacity: 0` in the code editor, hitting backspace, typing `1`, backspace, `0`, etc. The editor appears in an incorrect state after the new value each time.
