### ISSUE TITLE
Updating Node will screw with our packager server

### ISSUE THREAD

**Issue by balazsbajorics** [concrete-utopia/utopia#1739]
I was accidentally running v16.3.0 on my local dev env, and it produced hard-to-fathom issue with react-three-fiber and drei. 

I suspect that something changed about how npm resolves peer dependencies, or how the shape of node_modules folder is created.

Anyways, just a heads up, bumping our node version will probably mean the behavior of the packager system will break / change

**Comment by Rheeseyb** [comment]
Possibly relevant issue here (since the problem we were seeing was around drei using three, and class constructors needing to be invoked with 'new'): https://github.com/mrdoob/three.js/issues/21419
