### ISSUE TITLE
VSCode's user state cache can cause issues with our project state

### ISSUE THREAD

**Issue by Rheeseyb** [concrete-utopia/utopia#1770]
VSCode stores a cache of the user state in the `vscode-userdata-store`, which includes several keys related to the open project (`/User/state/<project_id>.json`, `/User/workspaceStorage/<project_id>/meta.json`, `/User/Backups/<project_id>/*`), which can clash with our project model when opening a project (leading to an occasional rogue conflict error message about the open file, or even undesired project forking).

We need to ensure that this cache does not overwrite files on load, or trigger saving / forking.

**Comment by seanparsons** [comment]
I've tried all sorts of combinations of forking, reloading and even disabling updates from VS Code reaching the editor and never once managed to reproduce this.
