### ISSUE TITLE
Potential (minor) security problem(s)

### ISSUE THREAD

**Issue by intrigus-lgtm** [concrete-utopia/utopia#1778]
Hi, could you please create a new [draft security advisory](https://help.github.com/en/github/managing-security-vulnerabilities/creating-a-security-advisory) and 
[invite me](https://help.github.com/en/github/managing-security-vulnerabilities/adding-a-collaborator-to-a-security-advisory) to it?
Any other private communication channel would also be fine.
I think I've found a potential (minor) security problem.

**Comment by maltenuhn** [comment]
Hey - thanks for reaching out and helping! I've just created & invited you to one.

**Comment by intrigus-lgtm** [comment]
Closing because https://github.com/concrete-utopia/utopia/security/advisories/GHSA-962x-7p54-c3pv has been opened.
