### ISSUE TITLE
Canvas, code, and CSS are inconsistent in this example

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1804]
STR

1. Add 8px padding to an element via the inspector, one property at a time. Result should be an object with `paddingLeft`, `paddingRight` etc.
2. In code, delete three of these props and change the remaining one to `padding`

Expected: the element has 8px padding on each edge
Observed: the code shows `padding: 8`. The inspector correctly shows all four properties set to `8`.  The canvas shows only padding top of 8

![image](https://user-images.githubusercontent.com/2945037/132847839-4f51b645-58bd-4969-a1bb-8f357ae693ed.png)

Possibly related to #1803

**Comment by seanparsons** [comment]
@maltenuhn I've tried several ways to edit the code, as well as going back and forth with undo/redo and never reproduced this.

**Comment by maltenuhn** [comment]
@seanparsons I now also can't reproduce this, along with #1803...

**Comment by maltenuhn** [comment]
Seems like we fixed this, along with #1803 and #1805. Closing.
