### ISSUE TITLE
Add a Canvas Loading Animation

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1824]
After some experiments here, I think the best thing is to just add the `shimmer` class (same we're using for the vscode iframe) to the container of the canvas (or the canvas itself, but then we need to make sure we don't have the backgroundColor set on it via `style` since it overrides the css classname.

(Other things I've tried: 
- adding it to a faked storyboard - rejected because it invites you to scroll etc, and when that doesn't work just feels broken
- showing a spinner or loading bar where the canvas is  (same issue as w/ the code editor)

**Comment by enidemi** [comment]
https://github.com/concrete-utopia/utopia/pull/1834
