### ISSUE TITLE
Pasting code with a hook leads to a canvas error

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1905]
STR

1. Into an existing component, add the line
 `const [width, setWidth] = React.useState(300);`

Observed: this error
Expected: works, re-renders appropriately.

![image](https://user-images.githubusercontent.com/2945037/136944461-ce7fcbfb-75e9-4ece-bcf0-606f2f4d1fd5.png)

**Comment by seanparsons** [comment]
Fixed in https://github.com/concrete-utopia/utopia/pull/1941
