### ISSUE TITLE
adding/changing App.propertyControls requires you to reload the editor

### ISSUE THREAD

**Issue by balazsbajorics** [concrete-utopia/utopia#1928]
we still seem to have some problem with the property controls iframe, if you open a new project, try to insert

```
App.propertyControls = {
  greetings: {
    type: 'string',
    title: 'Greetings',
    defaultValue: 'Hello World',
  },
  alpha: {
    type: 'slider',
    title: 'Amount',
    defaultValue: 0,
    min: 0,
    max: 100,
    step: 1,
  },
  backdrop: {
    type: 'color',
    title: 'Color',
    defaultValue: '#ddd',
  },
}
```

you will not see the changes in the inspector. you need to reload the editor to see the property controls

**Comment by Rheeseyb** [comment]
This should only be tackled in the context that it is currently a nuisance when developing the Inspector / the actual controls being used, meaning this should only be a quick fix or even a hack where possible (e.g. it could be a button for reparsing the controls, hidden behind a feature flag). The reason being that we don't want to encourage use of this style in general, as we want to remain free to experiment with and completely change the way in which users can define property controls until we are happy with them.

**Comment by Rheeseyb** [comment]
Now no longer an issue
