### ISSUE TITLE
Moving mouse while typing classname selects class

### ISSUE THREAD

**Issue by BLamy** [concrete-utopia/utopia#2348]
**Describe the bug**
Moving mouse while typing classname selects class

**To Reproduce**
Steps to reproduce the behavior. For canvas tasks, take care to note down all relevant key holds, keys typed, selected state etc. E.g:

1. Start new project
2. Add tailwind to project
3. Begin typing a className
4. Move mouse

Result: The current suggestion is selected and added to the list

**Expected behaviour**
nothing

**Screenshots**
![moving mouse selects class suggestion](https://user-images.githubusercontent.com/324928/175168455-e1682c64-c8f7-4629-8799-58dc3b4e6c0b.gif)

**Comment by balazsbajorics** [comment]
oops, I reopen this because I'm actually not sure if this is fixed yet

**Comment by balazsbajorics** [comment]
@BLamy we believe that #2351 fixed the issues, so I'm closing the ticket. 
Thank you for reporting it, and thanks for taking the time and effort to make a video, and submitting PRs! 🌟
