### ISSUE TITLE
CSS importing is tied to eager evaluation

### ISSUE THREAD

**Issue by Rheeseyb** [concrete-utopia/utopia#252]
Follow on from #142. Blocked by #249.

Right now CSS files imported by other files in the project will be slipped into the DOM due to eager evaluation. As well as this, removing those imports will then _not_ unload that CSS.

We need to either not eagerly load this CSS files transitively, or clear them from the DOM when opening a canvas file.

On top of this, the _only_ reason we are even loading CSS files that are imported in the canvas file is because of the `getExportValuesFromAllModules` evaluating the currently open file after a change is made to it.

**Comment by seanparsons** [comment]
Appears to be fixed by https://github.com/concrete-utopia/utopia/pull/526 as there is already existing work to unload CSS files from the canvas.
