### ISSUE TITLE
error to run utopia

### ISSUE THREAD

**Issue by d0uub** [concrete-utopia/utopia#2586]
i run it in docker (nixos/nix) with below error..
![image](https://user-images.githubusercontent.com/12244281/192447096-7d45426b-b8a4-4d76-96bb-90931f2b440d.png)

how can i make it works? thanks

**Comment by d0uub** [comment]
it is proxy problem, resolved.

**Comment by Rheeseyb** [comment]
Sorry about the delayed response, we must have overlooked this one yesterday. I'm glad to hear you resolved it.
