### ISSUE TITLE
code editor not work

### ISSUE THREAD

**Issue by d0uub** [concrete-utopia/utopia#2591]
everything smooth but cannot load the editor, i want to use this tools.. 
any suggestion?
![image](https://user-images.githubusercontent.com/12244281/192694743-86c3f478-6c7a-4363-804c-7779bb2990f0.png)

**Comment by Rheeseyb** [comment]
Hey, it's hard to tell from this, but one thing that is really striking me is that the font is incorrect in that console tab. This combined with the previous issue you posted #2586 makes me wonder if this too is a proxying issue. The code editor pane runs inside an iframe which is served on port 8001, so if that port isn't accessible then that may be an issue.

If you open the Chrome Devtools can you see any other errors in that console, or any failed requests in the network tab?

If you're able to join our Discord server (https://discord.gg/NEEnPKCgzC) that may be a better option for seeking help with this as (depending on your timezone) we'll try to provide some more real time help to get you set up.

**Comment by d0uub** [comment]
resolved by change endpoint from http://localhost:8000/p to http://127.0.0.1:8000/p
that would be great if there have docker image to pack everything up
