### ISSUE TITLE
CMD + / incorrectly comments out JSX

### ISSUE THREAD

**Issue by alecmolloy** [concrete-utopia/utopia#284]
STR:
1. Insert cursor on a line with JSX
2. press CMD + / 

Expected: line is commented out using JSX comment syntax
Actual: line is commented out using JS single-line comment, which does not work

e.g.:
```
     <View />
```
becomes:
```
     // <View />
```
instead of:
```
     {/* <View /> */}
```

**Comment by maltenuhn** [comment]
Probably fixed with switch to VSCode, verify

**Comment by Rheeseyb** [comment]
Closed with the move to VS Code
