### ISSUE TITLE
If I close the structure tab I can't open it again.

### ISSUE THREAD

**Issue by Jbrandan** [concrete-utopia/utopia#3198]
> If I close the structure tab I can't reopen it.

![image](https://user-images.githubusercontent.com/41725603/215292783-f981a6fe-6309-4b1c-aa45-70b55e059b6a.png)

> I looked in the options of this tab but none take effect.

![image](https://user-images.githubusercontent.com/41725603/215292849-8504a5e3-4a44-4ac8-b6bf-b636f74b9216.png)

**Comment by maltenuhn** [comment]
We'll fix this, but `CMD+option+1` lets you toggle it!
