### ISSUE TITLE
Spike to determine the scope of the issue of eager evaluation

### ISSUE THREAD

**Issue by Rheeseyb** [concrete-utopia/utopia#510]
Where and why do we perform eager evaluation?
1. As part of determining exports
2. To build code result cache (after a build message from the ts worker)

What problems does it actually cause?
1. Performance
2. Mutation via side effects:

`a.js`
```
export let A = 100
```
`b.js`
```
import { A } from './a'
A = 7777
```
`app.js`
```
/** @jsx jsx */
import * as React from 'react'
import { Scene, Storyboard, View, jsx } from 'utopia-api'
import { A } from './a'
export var App = (props) => {
  return (
    <View
      style={{ width: '100%', height: '100%', backgroundColor: '#FFFFFF' }}
      layout={{ layoutSystem: 'pinSystem' }}
    >
      {A}
    </View>
  )
}
export var storyboard = (
  <Storyboard layout={{ layoutSystem: 'pinSystem' }}>
    <Scene
      component={App}
      props={{}}
      style={{ position: 'absolute', left: 0, top: 0, width: 375, height: 812 }}
    />
  </Storyboard>
)
```

In `app.js`, the value of `A` should be `100`, but is `7777`

3. ReactDOM.render in an `index.js` - seems to only be an issue if trying to render to the `'editor'` node
4. Exceptions thrown - we're wrapping in a try catch so shouldn't be an issue

**Comment by seanparsons** [comment]
Closing due to spike above.
