### ISSUE TITLE
After a few edits, our Github integration shows all files as modified

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#5248]
Problem: a few specific edits cause this issue.

We have both **false positives** (shown here) and **false negatives** (where a definitely modified and saved file shows as not modified). It's truly shocking.

![Image](https://github.com/concrete-utopia/utopia/assets/2945037/74dedc1c-7669-4ec4-b7f4-408f0cee9e0d)

**Comment by balazsbajorics** [comment]
not sure if related:

I've seen the Github integration in a weird internal state where it forgot the commit history, and pushing a first commit to a new branch showed up in the git repo as an origin commit without any link to the main branch.

maybe this happens here too?

**Comment by gbalint** [comment]
Moving back, maybe this is has been fixed by https://github.com/concrete-utopia/utopia/pull/5280
