### ISSUE TITLE
Active Pages tab in the lefthand menu should *not* navigate to the navigator

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#5250]
The editor currently selects the navigator tab when users take action on the canvas. That's nice and useful after you've eg used the settings or files tabs, but for the pages one it's tedious. 

Solution: active pages tab doesn't yield

**Comment by bkrmendy** [comment]
For reference, this PR added the feature so it's a good starting point for tweaking it https://github.com/concrete-utopia/utopia/pull/4381
