### ISSUE TITLE
Check the state of supporting remix routes with query params

### ISSUE THREAD

**Issue by balazsbajorics** [concrete-utopia/utopia#5256]
figure out what is the overall state of query parameter and hash param support for Remix Routes in utopia

make a project that has internal routes with query params. try to link to these routes, click on the routes. what happens? 
- [ ] does navigation work?
- [ ] do we load the query param? 
- [ ] does the query param show up in the URL bar?
- [ ] what if you have project code that sets the query param value?
- [ ] Does the Pages tab still show the correct URL highlighted?
- [ ] If you put query params in the favorites in `package.json`, does _that_ work?

Please try to be comprehensive, and go beyond basic "it doesn't crash utopia if I do this one thing" approach

https://remix.run/docs/en/main/guides/data-loading#url-search-params

**Comment by bkrmendy** [comment]
Tested on the Hydrogen sample store, the `/products/:handle` routes have query params such as `?Size=Small&Color=Green`.

- Does navigation work?: ✅ Yes
- Do we load the query param? ✅ It's handled by react-router, we don't deal with it directly
- Does the query param show up in the URL bar? ❌ No, just the path name. 
- what if you have project code that sets the query param value? The variant picker sets the query param (as in it doesn't add a new navigation step), we detect the changed query params, and the page state is updated
- Does the Pages tab still show the correct URL highlighted?
  - Yes, correct as in the route with the matching path name is highlighted.
  - However, if there's another favorites entry with the same path name but with a query param set, the favorite with the query param is not highlighted
- If you put query params in the favorites in package.json, does that work? Yes and no:
  - Navigating to the route with the right query params works (it navigates to the variant that's specified by the query param)
  - The favourites section looks weird:

![Image](https://github.com/concrete-utopia/utopia/assets/16385508/93c1bf5d-2618-4c39-89b2-2f89ef74b4c3)
