### ISSUE TITLE
Add `moduleName` to `PreferredContents`

### ISSUE THREAD

**Issue by bkrmendy** [concrete-utopia/utopia#5267]
When the component picker looks for the icon of a registered component, without knowing which module it came from, the icon of the first registered component will be returned, which might not be the right one. To fix this, we need to add a `moduleName` prop to `PreferredContents`, which tells the component picker which module that component is coming from.

**Comment by gbalint** [comment]
Moving back, maybe this is has been fixed by https://github.com/concrete-utopia/utopia/pull/5280
