### ISSUE TITLE
exporting / importing a component from a second file crashes the editor, can't be recovered

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#529]
Example project here (it won't load, you'll get the console though): https://utopia.pizza/p/cca2aee9-invincible-century/

STR: 
1. Have code in `App.js` that imports a component from, say, `icons.js` (which doesn't exist yet)
2. Create `src/icons.js`
3. Paste example code into it that exports a component

Result: crash, unrecoverable.

**Comment by Rheeseyb** [comment]
This appears to have been fixed by #562 (currently in review) and #544

**Comment by Rheeseyb** [comment]
Closed by the above two PRs
