### ISSUE TITLE
Tweak `html` and `head` element handling in Navigator

### ISSUE THREAD

**Issue by Rheeseyb** [concrete-utopia/utopia#5291]
- The `html` row in the navigator should by default be non-selectable (using the lock icon), so `body` becomes the ‘outermost div’ you can select
- The `head` element should not expand its children by default

**Comment by ruggi** [comment]
Amended:

> ~~The html row in the navigator should by default be non-selectable (using the lock icon), so body becomes the ‘outermost div’ you can select~~

The html row in the navigator should by default be locked
