### ISSUE TITLE
Create the promo panel for three projects

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#5328]
**Problem**
We're relying on the arcane github clone URL for people and collaborators to fork the sample project(s). 

Implement the promo panel to create 
- [ ] a new empty public project
- [ ] a new public remix-only project
- [ ] a new public H2 project

If this is implemented via github clone, please update the readme and quickstart with clear instructions for how to get this to work locally from a vanilla setup - right now it does not.

<img width="953" alt="Screenshot 2024-04-19 at 11 00 14 AM" src="https://github.com/concrete-utopia/utopia/assets/47405698/da6bf042-2cc2-4114-b32d-656d0fcbd505">

[figma explorations](https://www.figma.com/file/3oVghRhlAIIeD11CLmN5LJ/Multiplayer-II?type=design&node-id=5%3A102&mode=design&t=C0s0bAFwc4JRsyOT-1)

**Comment by maltenuhn** [comment]
@lankaukk could you add your design / link to the design? Specifically the one that does _not_ do this via buttons, but via the "featured projects" panel

**Comment by lankaukk** [comment]
> @lankaukk could you add your design / link to the design? Specifically the one that does _not_ do this via buttons, but via the "featured projects" panel

Added the screenshot, I hope this is the one you meant!
