### ISSUE TITLE
cmd+s doesn't seem to reliably save the project

### ISSUE THREAD

**Issue by Rheeseyb** [concrete-utopia/utopia#534]
From Slack:

> I press cmd + s
> then I wait a bit
> then I press reload
> warning dialog comes up
> I press reload anyway
> data is lost
> what I usually do is I copy my app ui js contents
> and keep pressing cmd + s + reload until the dialog does not come up

**Comment by maltenuhn** [comment]
Possibly related to the brittleness here?

- new project, trying to close it as soon as the welcome tab finished loading triggers the alert
- opening a new project, clicking on the app.js tab, clicking back to the Welcome tab, triggers the alert when trying to close
- new project, making a change to a code file via the design tool and then undoing it with CMD+Z correctly "resets" the dot, but triggers the alert when trying to close

**Comment by balazsbajorics** [comment]
extra information: it seems like pressing cmd + s in the _code editor_ does not trigger a project save! pressing cmd + s on the canvas does seem to do the trick

**Comment by Rheeseyb** [comment]
As part of debugging some of the github import issues I noticed that `cmd`+`s` in the code editor triggers a project save, but doesn't include the updated model in the request sent to the server. Picking this up now.
