### ISSUE TITLE
When loading a github-connected project, the github pane claims there's no remote changes. this takes up to a minute to resolve and show the changes

### ISSUE THREAD

**Issue by balazsbajorics** [concrete-utopia/utopia#5383]
![Image](https://github.com/concrete-utopia/utopia/assets/2226774/096cd041-bff4-4851-bab1-8bbcd66740d5)

makes me want to murder the editor

**Comment by balazsbajorics** [comment]
draft fix here #5389 

@ruggi what's the status on this one?

**Comment by ruggi** [comment]
https://github.com/concrete-utopia/utopia/pull/5389 is taking care of that, in progress :)
