### ISSUE TITLE
Replace the contextual insert menu (+ within flex) with the new insert context menu

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#5396]
Notes: 

![Image](https://github.com/concrete-utopia/utopia/assets/2945037/716aa209-34a3-45c8-8475-d07e4a5491c4)

Once this is done, please ping @maltenuhn to check if there are other places we might still need the Classic insert menu.

Separately: we still want draw-to-insert (and the insert mode that comes with it), but _not_ for arbitrary components. Per @liady 's observation, we probably need to harden the handling of that _mode_ - but it's possible that the mode is fine and instead the react-select-driven toolbar insert menu is the issue.

> when we have the floating "Insert" menu already visible, the openFloatingInsertMenu action doesn't re-open the insert dropdown (the React component doesn't even re-render). Notice that on Selection mode it works, but in Insert mode it doesn't

**Comment by Rheeseyb** [comment]
Fixed by #5458
