### ISSUE TITLE
Make the Component Picker scroll bar show up

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#5411]
Follow-up to https://github.com/concrete-utopia/utopia/issues/5427

We suppress scroll bars deliberately for most editor UI, to handle overflow for eg tab containers and other small areas. This is in `initial-load.css`, line 40: `::-webkit-scrollbar { display: none; }`

However, for scrollable lists specifically - like this one - we should show them. I haven't figured out a way to do that though! :) 

FWIW we normally try to avoid styling via global classes, but if that's what is expedient here (eg `.show-scrollbar`) we can do that.

**Comment by maltenuhn** [comment]
@benwolfram I've tagged you here since this completely dovetails w/ what you're already working on (and because I failed to solve this :D ) Feel free to un-assign yourself, or even roll it into your WIP as you see fit!

**Comment by liady** [comment]
@benwolfram I fixed it since I was looking into my other task, the fix PR is here #5457
