### ISSUE TITLE
Parent's "children content" outlines should only draw if all children are fully contained inside parent

### ISSUE THREAD

**Issue by Rheeseyb** [concrete-utopia/utopia#5471]
I'm pretty sure this was a deliberate decision (something around showing the origin of the content?), but it looks bad, and it should go in the bin

MN reply: we wanted to show the outer bounds of all content inside a container (so you can kinda see eg where padding is), obvs assuming the container is well-behaved and the outer container bounds are visually larger or equal to the dimensions of its contents.

- [ ] Investigate if that's actually what's going on here (why are there things inside of `body` that are not inside it? maybe the cart? or scrollable content?)
- [ ] If that's indeed the issue:
  - [ ] only show those bounds if ALL (not! ANY) EDGES are inside the parent or match its edges, and AT LEAST ONE is further inside it. This will avoid distraction
  - [ ] if easy to do, ignore zero-sized elements from this calculation (this might be the issue with the first screenshot)

Selecting body:
![Image](https://github.com/concrete-utopia/utopia/assets/2226774/4df47213-e8fe-4884-8a8e-538fb5387293)

Selecting Column:
![Image](https://github.com/concrete-utopia/utopia/assets/1044774/fcee9f9b-a82d-4fcf-8ba0-9dd0f9c8cafa)

**Comment by maltenuhn** [comment]
@Rheeseyb I edited the description, can you fact-check pls?
