### ISSUE TITLE
Sometimes, VSCode stops printing / showing edits

### ISSUE THREAD

**Issue by balazsbajorics** [concrete-utopia/utopia#5476]
maybe clue: after a non-printing incident happens, the highlight bounds no longer match the printed text in vscode, as if the highlight bounds use the printed text whereas vscode keeps showing the old text

**Comment by maltenuhn** [comment]
@Rheeseyb and @seanparsons  I tagged you here to reserve, re-assign or pair up w/ anyone as needed

**Comment by Rheeseyb** [comment]
Closed by #5517
