### ISSUE TITLE
Setting minHeight prop on Section selects the next section

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#5477]
STR in the video https://screenshot.click/02-35-wl9np-qgyee.gif

Issue is that after ticking the minHeight box, we have two `<Section padded minHeight />` in the project - same hash. We then lose selection, and select the **second** one.

**Comment by Rheeseyb** [comment]
This one will not be solvable in a 2 hour timebox, so do we increase the timebox or de-prioritise it @maltenuhn ?
