### ISSUE TITLE
The various 'row' and 'column' components have the wrong icon in the insert menu

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#5502]
See here: all right now use the 'component' icon. 
- [ ] They should use the correct icon from the annotations
- [ ] If that's already the case, the component annotations should be amended to use the right icons

![Image](https://github.com/concrete-utopia/utopia/assets/2945037/ce44296f-f5e5-434d-9c53-ab376c2f21dc)

**Comment by Rheeseyb** [comment]
They aren't set, so I'll update them

**Comment by Rheeseyb** [comment]
Done
