### ISSUE TITLE
Only component props connected to data should be blue

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#5560]
_MN: re-opening because only the (now deleted) title part was addressed_

_NB: data means a js var or const (it does not mean a JSX element)_

**Component Definitions**
_Not connected to data_
- [ ] Per below screenshot: _none_ of these are connected to data, so none should be blue
- [ ] Hover state should be blue text and plus icon, cursor `pointer`

_Already connected to data_
 - [ ] If connected to data, show blue text only
- [ ] Hover state should be blue text and plus icon, cursor `pointer` (same)

![Image](https://github.com/concrete-utopia/utopia/assets/2945037/5a4a0bab-caee-41ef-97bb-7e239d6110bf)

**Comment by maltenuhn** [comment]
@ruggi are you still working on this? If so, what's the status?

**Comment by ruggi** [comment]
> @ruggi are you still working on this? If so, what's the status?

yeah - https://github.com/concrete-utopia/utopia/pull/5581
