### ISSUE TITLE
"List" should be a default option in the insert menu

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#5605]
Since that that cannot be user-specified, we should provide it and add it to the bottom of his insert menu, above "More"

![Image](https://github.com/concrete-utopia/utopia/assets/2945037/15df82f2-2a5b-420f-98e9-99443cf47afc)

**Comment by gbalint** [comment]
This is non-trivial, because the value parser used in the descriptor file parsing recognizes the map as ATTRIBUTE_OTHER_JAVASCRIPT and not JSX_MAP_EXPRESSION

**Comment by maltenuhn** [comment]
I'm gonna unblock this
