### ISSUE TITLE
Support `export default function App()` syntax

### ISSUE THREAD

**Issue by Rheeseyb** [concrete-utopia/utopia#561]
Defining a component with no props results in us parsing it as an arbitrary piece of code, rather than a component. This causes issues with a number of basic React examples, since a lot of them define their main component using the syntax
```
export default function App() {
```

~This can cause the navigator to not render (#560), and build errors due to circular dependencies. See the below comment for the root cause. This also causes problems with the navigator not rendering.~

~Repro project showing build errors due to a circular dependency https://utopia.pizza/p/43a26dec-psychedelic-archaeology/~

**Edit:** Description has been updated, and the other issues that were previously in this ticket have been extracted into #567 and #568

**Comment by Rheeseyb** [comment]
This again appears to be caused by the `export default function App()` (changing that to `export function App()` resolves the issue)

**Comment by maltenuhn** [comment]
Ok, we should probably support that syntax since it's the default CRA one. I'll update this ticket and reference the other one.

**Comment by Rheeseyb** [comment]
I'm going to move this under the "Support running valid react code in the canvas" part of the roadmap

**Comment by maltenuhn** [comment]
I've also just created that as a Milestone and assigned it. Not sure how helpful they are, but this project seems pretty predictable and linear like that.
