### ISSUE TITLE
Make style section hideable and suppressable

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#5635]
**Problems**
- The style section and its subsections are difficult to work with and understand, especially for components. 
- Additionally, the completely hiding the style section was not well received.

**Solution**
_Part 1_
- [x] Create a new "Styles" (sic) Section
- [x] Make that capable of folding in and out **the entire set of existing style subsections**
- [x] use the Utopia API to expand, collapse, or hide this new section (bikeshed the naming)

_Part 2_
- [x] Create a new Section called "Advanced"
- [x] Relabel the Target Selector subsection / component as "Target" (not 'style')
- [x] Relabel the CSS Classname subsection (the one we show when Tailwind is enabled) as 'CSS'
- [x] Move them into the "Advanced" section
- [x] Make the 'advanced' subsection closed contracted by default (so you don't see the Target and CSS subsections

_Part 3: Defaults and Component API_ 
- [x] For components, collapse the new Styles section by default. 
- [x] API should allow showing it as collapsed, expanded, and hidden (bikedshed labels...), and section should respect that
- [x] for elements, expand the Styles section by default

**Comment by bkrmendy** [comment]
https://github.com/concrete-utopia/utopia/pull/5714 adds the component API prop to expand/collapse/hide the Style section

**Comment by bkrmendy** [comment]
https://github.com/concrete-utopia/utopia/pull/5723 adds the component API parts
