### ISSUE TITLE
Look into project load performance

### ISSUE THREAD

**Issue by balazsbajorics** [concrete-utopia/utopia#5637]
Broadly, we're curious what happens - and how long it takes - when 
a) loading an existing hydrogen-november demo store project
b) github cloning a fresh hydrogen-november 

from 'click' to 'everything is rendered on the canvas', what are the steps, how long they roughly take, what's the flow, which thread is blocked (main thread or a worker etc)

**Comment by liady** [comment]
These are some preliminary findings - if they're helpful:

`getParseFileResult` takes 14s for two consequtive runs (maybe we can parallel):
![Image](https://github.com/concrete-utopia/utopia/assets/7003853/713c7d92-2d24-476b-80be-d893295ba692)

Seems like `parseArbitraryNodes` takes most of time:
![Image](https://github.com/concrete-utopia/utopia/assets/7003853/b1225078-5a85-431b-bb05-8e7aa6a609a7)

A lot of self time in `object-hash` - maybe we can optimize there:
![Image](https://github.com/concrete-utopia/utopia/assets/7003853/779a627e-6de1-4a40-a8af-b5cd0cdfdba6)

**Comment by seanparsons** [comment]
First load of a Hydrogen project:
- `LOAD` action is fast, but dispatching it takes over a second.
- 19 seconds to parse all the files in the project.
- 2 seconds to dispatch the `MERGE_WITH_PREV_UNDO` action which pulls in the parsed files.
- Then canvas renders.

Didn't really track anything during the rest of the startup prior to the `LOAD` action as it's not hugely relevant to this.

**Comment by seanparsons** [comment]
Github load of the same Hydrogen project:
- 9 seconds to pull the branch content from Github through the server.
- 9 seconds to parse all the files in the project.
- 1 second to save the assets (locally and going to disk not S3).
- 1 second later the canvas renders a number of times.
- 2 seconds to refresh the dependencies (when already cached locally).
- Canvas renders again.

**Comment by seanparsons** [comment]
For the main parse there's not currently one big headline performance issue, it's a mix of the following:
- Hashing to get consistent UIDs, which even completely disabling saves us only 2s out of 10s.
- There's a few parts where we twiddle source maps which are pretty costly, perhaps an upgrade of the library for this will help.
- A lot of cases of transforming code with Babel, which are hard to do anything about.
