### ISSUE TITLE
component API should support `label` for components

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#5647]
**Problem**
Most things in our API support (optional) labels, except for components themselves.

The label should be used 
- [ ] as the default label in the inspector (check w/ @ruggi for the design since he worked on a partial implementation already)
- [ ] above the component section (If we have the label from component definitions, use that as the main label, and then show the code name after

**Comment by bkrmendy** [comment]
This PR adds the `label` prop to `ComponentToRegister` https://github.com/concrete-utopia/utopia/issues/5647

**Comment by bkrmendy** [comment]
Prior art: https://github.com/concrete-utopia/utopia/issues/5560

**Comment by bkrmendy** [comment]
this PR adds the UI https://github.com/concrete-utopia/utopia/pull/5670
