### ISSUE TITLE
Component API should support string field for `folder`

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#5649]
- [x] Instead of folder control, each prop should support an (optional) `folder` field (string)
- [x] the folder control need no longer be supported by the API at all
- [x] No parsing of the label to create subfolders; hence, no sub-folder support
- [ ] the inspector is populated _first_ by folder-less components, then by foldered ones, _in order of appearance_  ('first time the particular folder label shows up when iterating over the props').
- [ ] folders are open by default, except if label matches exactly 'Advanced' (that is closed by default)

**Comment by bkrmendy** [comment]
This PR adds the folder labels/removes the folder control https://github.com/concrete-utopia/utopia/pull/5651
