### ISSUE TITLE
Investigate supporting other versions of React

### ISSUE THREAD

**Issue by Rheeseyb** [concrete-utopia/utopia#565]
We previously came to the conclusion that we wouldn't be able to support React <17, but either way we also need to see if we can support experimental builds (for a lot of the R3F examples), and if so how. Alec shared this mega useful link that shows an example of using React 17 on the outside to, and React 16 on the inside: https://github.com/reactjs/react-gradual-upgrade-demo/

**Comment by seanparsons** [comment]
Results of investigation recorded into document.
