### ISSUE TITLE
Data Children: show props.children in the inspector component section

### ISSUE THREAD

**Issue by balazsbajorics** [concrete-utopia/utopia#5686]
**Problem:**
it feels weird to see `name` as a data cartouche in the navigator for `<h2>{name}</h2>`, but the inspector's component section is empty. we want the component section to be able to show anything which might require data picking!

**proposed solution:**
Show props.children as a separate entry at the bottom of the component section!

Question: should we show the component section with props.children for selected elements which would otherwise not show the component section, such as div, h1, h2, etc? I personally feel like yes we should

**Comment by gbalint** [comment]
We should do this in a way that it takes the component annotations into account:
- if the annotations says children are not supported, do not show the children control
- if the annotations says the preferred contents is text, show  a string input not a jsx input

Maybe we should even extend the API so you can associate a custom control to the children prop (e.g. if you want define a custom label, or put it into a folder, or add a segment control to choose between options, etc).
