### ISSUE TITLE
Fix styling of the sample store in utopia

### ISSUE THREAD

**Issue by gbalint** [concrete-utopia/utopia#5697]
You can find the utopia-compatible sample store here: https://github.com/concrete-utopia/hydrogen-may/tree/sehl-utopia
You can compare it to the real store in local dev environment or on https://utopia-1e8ff9861eb8a6796b14.o2.myshopify.dev/

Main page looks like this:

![Image](https://github.com/concrete-utopia/utopia/assets/127662/d0c5d81e-5e76-43dd-8f74-ee92663b14ec)

Instead of this:

![Image](https://github.com/concrete-utopia/utopia/assets/127662/683e0c78-6100-4c81-abdf-766c4d610521)

And the product page (click on the tote bag) is even worse, see e.g. 

![Image](https://github.com/concrete-utopia/utopia/assets/127662/568aa748-7193-4b21-986f-2fce47b1e06a)

instead of:

![Image](https://github.com/concrete-utopia/utopia/assets/127662/13de8f2b-9afc-46c0-b863-2bc6fe1d7ff9)

**Comment by Rheeseyb** [comment]
Final layout issues fixed by removing `whitespace-pre-wrap` <https://github.com/concrete-utopia/hydrogen-may/pull/1/commits/67d7c14231a13fdb2c7d2421c1bfd3cc9edd11ef>
