### ISSUE TITLE
Check why we needed to add lots of React imports to the sample store project

### ISSUE THREAD

**Issue by gbalint** [concrete-utopia/utopia#5699]
I added React imports to basically all files until these errors disappeared:

![Image](https://github.com/concrete-utopia/utopia/assets/127662/bf63523c-b7b5-4134-a251-0ff8f048381f)

See https://github.com/concrete-utopia/hydrogen-may/commit/e0510771076eee95e57b5a543b3cf3923d9cdc4c

But valid react projects should work without additional imports

**Comment by seanparsons** [comment]
Removing the imports and even rolling back my code a couple of days and I wasn't able to reproduce this...
