### ISSUE TITLE
Navigation is broken in the new hydrogen project after navigating to the product page

### ISSUE THREAD

**Issue by Rheeseyb** [concrete-utopia/utopia#5718]
After navigating to the product page in the new hydrogen project, navigation to other pages becomes impossible. This _may_ be related to #5709 

https://github.com/concrete-utopia/utopia/assets/1044774/2eafb4fd-15a0-4b56-b461-35096cedd0b4

**Comment by Rheeseyb** [comment]
Ok, confirmed that this is indeed caused by the `Accordion` component, which is the cause of the issues in #5709

**Comment by Rheeseyb** [comment]
Actually, I'm going to re-open this and assign to Sean so that it is tracked and we can verify the fix to #5709 fixes this too

**Comment by seanparsons** [comment]
At one point I found that the fix for #5709 didn't fix this, but now it appears that we're not using the component in the latest version of the project but also now testing it again something has changed such that the old project I had to use doesn't work with the latest editor code.
