### ISSUE TITLE
hydrogen-may project sehl-utopia branch: font is missing in utopia

### ISSUE THREAD

**Issue by gbalint** [concrete-utopia/utopia#5754]
Original:

![Image](https://github.com/concrete-utopia/utopia/assets/127662/44289774-4742-40f6-8d26-104cfcd48257)

Utopia:

![Image](https://github.com/concrete-utopia/utopia/assets/127662/bfe38a6a-b3e9-4514-8a04-c9a14e9d62a9)

**Comment by seanparsons** [comment]
Fixed by https://github.com/concrete-utopia/utopia/pull/5760 it would appear.
