### ISSUE TITLE
RecoilRoot kills the navigator / controls.

### ISSUE THREAD

**Issue by balazsbajorics** [concrete-utopia/utopia#579]
https://utopia.pizza/project/6222d0f3/

The presence of RecoilRoot makes the navigator empty. My bet is that it has something to do with DOM walking.

**Comment by balazsbajorics** [comment]
you can see that with a removed RecoilRoot, it starts working: https://utopia.pizza/p/d0769e2b-youthful-goldenrod/

**Comment by seanparsons** [comment]
Duplicate of https://github.com/concrete-utopia/utopia/issues/560
