### ISSUE TITLE
Inspector: Use relevant icons for the Row / Column component inspector

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#5851]
**Problem / Before**
![Image](https://github.com/concrete-utopia/utopia/assets/2945037/72b5ca7c-dd37-437a-aa73-05b14a67b44a)

**Solution / After**

![Image](https://github.com/concrete-utopia/utopia/assets/47405698/ce873938-fcb9-4903-a758-53922dc59ea7)

- [x] find these icons files in the `inspector-element` subfolder
- [x] then add them to the `UtopiaIcons` in `icons.tsx`
- [ ] use them in the inspector component prop controls

**Comment by gbalint** [comment]
Note: now it is called Row and Column (not Flex)
