### ISSUE TITLE
the Layout component in hydrogen-may shows up with the wrong size, until it is focused, then its displayed size changes

### ISSUE THREAD

**Issue by balazsbajorics** [concrete-utopia/utopia#5856]
This is a problem in how we measure the size of unfocused and focused components which wrap their children in a thick layer of wrapper elements.

It is particularly problematic in the sample project, because it _always_ shows up, and looks clearly incorrect because the outline visibly does not line up with what's rendered on the screen.

**Comment by seanparsons** [comment]
Mitigation for the issue added to the project here: https://github.com/concrete-utopia/hydrogen-editions-24/pull/11

**Comment by seanparsons** [comment]
Diagnosis of the cause:
- It's defined with an `Outlet` as a child, which inside the component itself goes inside a fragment that makes up the return and inside that in a main element.
- That means we statically identify the `Outlet` as a child, which then accounts for its size when unfocused.
- However when we focus it, all the actual contents then get added into the metadata.
- When focused, by the power of recursion (and for the sake of simplicity putting to the side some inconsequential elements) the size for `Layout` ends up being effectively the size of the `Outlet` and the size of the `Footer`.

![image](https://github.com/concrete-utopia/utopia/assets/217400/2647e319-e508-4f84-92ae-94186bf80c1d)
