### ISSUE TITLE
Resizing any pane (left, right, code editor) to zero should hide it and reset the size to default

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#5876]
**Problem**
We had issues with unresizable or permanently hidden columns. Turns out that one of the causes is that the code editor can occasionally be resized to zero _but not hidden_ - meaning you can restore it by clicking on an invisible zone and resizing it. This is not optimal.

**Solution**
Similar to before, we should implement a logic where 
- any size that's zero means the resulting element is hidden (similar to pressing the red button)
- no size 0 is ever persisted
- any hidden thing that's no longer hidden should not retain a size that's below 100px

Verify that cmd+option+1 and cmd+option+2 also do the right thing

**Comment by liady** [comment]
does this make sense as a fix (setting min width to 100px)?
https://github.com/concrete-utopia/utopia/commit/e387bbdad4a422f0996b6079e5e817e9fc2f37ca

**Comment by maltenuhn** [comment]
Are there other entry points that can affect the size? In the previous implementation there were (eg a resize of one thing could affect another), so a simple check _on resize_ was not enough. I don't know enough about the current implementation tho.
