### ISSUE TITLE
Array cartouche tweak

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#5910]
**Problem**
We currently show the pink override state everywhere. The number should use the non-emphasized state by default, and only use the pink color when it's overridden (currently only possible in the navigator)

**Comment by maltenuhn** [comment]
@lankaukk could you re-add the relevant designs here?

**Comment by lankaukk** [comment]
<img width="1053" alt="Screenshot 2024-06-13 at 10 15 42 AM" src="https://github.com/concrete-utopia/utopia/assets/47405698/c7e543e8-1f72-4e32-af46-9e3613faeca9">
