### ISSUE TITLE
Data Picker: show Promises in a way that it’s clear that they are promises

### ISSUE THREAD

**Issue by balazsbajorics** [concrete-utopia/utopia#5946]
if useLoaderData contains promises, the data picker should show these promises as Promises, to indicate these are not readily insertable or traversable.

the way to detect a promise is that it has a `then` key and the value is a function

**Comment by bkrmendy** [comment]
a lightweight approach: https://stackoverflow.com/questions/27746304/how-to-check-if-an-object-is-a-promise/27746324#27746324
