### ISSUE TITLE
Data Picker Bug: For some reason some objects are not traversable, they become leafs. I believe this is behavior of the existing code, needs investigation

### ISSUE THREAD

**Issue by balazsbajorics** [concrete-utopia/utopia#5947]
![Image](https://github.com/concrete-utopia/utopia/assets/2226774/11ce95b5-7279-44a1-9316-a7540e5a0d9f)

on the builder-tote Product page, data.variants.nodes[0].selectedOptions[0] should be further traversable and not a leaf!!

**Comment by bkrmendy** [comment]
I tlooks like this issue fixed itself in the meantime: 

![Image](https://github.com/concrete-utopia/utopia/assets/16385508/b85699ac-29f4-4f6b-9554-bbcc5326cc5d)
