### ISSUE TITLE
selecting content underneath the header does not work

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#5964]
**Problem**
(open ended) trying to select content underneath stuff rendered by the Layout component is not possible even w/ cmd-click
We probably need a way to annotate such extraneous, non-editable content in some way

Project link: https://utopia.pizza/p/960ac92c-concrete-utopia-hydrogen-editions-24/

![Image](https://github.com/concrete-utopia/utopia/assets/2945037/3cda1d98-be47-4813-9c67-3bacd4eaef04)

**Comment by gbalint** [comment]
First step:
[ ] fix locking so you can select the element behind a locked element

After this fix, we can persist the locking and/or add component annotation about autolocking the internals of a component.
