### ISSUE TITLE
Add Drag to Duplicate to grid reordering

### ISSUE THREAD

**Issue by lankaukk** [concrete-utopia/utopia#6034]
We have a strategy that duplicates a selected element when you hold option and drag, and you also see a special cursor. This functionality should also be available when reordering grid items.

**Comment by maltenuhn** [comment]
I'm gonna close this since we're tracking these issues through a doc instead, it's reflected there already

**Comment by ruggi** [comment]
implemented in https://github.com/concrete-utopia/utopia/pull/6036
