### ISSUE TITLE
vscode navigates to selection after canvas interaction even when selection has not been changed

### ISSUE THREAD

**Issue by gbalint** [concrete-utopia/utopia#6113]
Not necessarily a bug, but it can be annoying.

- Select an element on the canvas
- Navigate away in vscode
- Do something on the canvas with the element, e.g. resize it
- Vscode will navigate back to selection after printing is ready (even though the selection has not been changed)

If printing is slow, it can happen that you start to edit something in vscode, and then it suddenly navigates away, very annoying.

See https://screenshot.click/16-23-mu5me-aa5zp.mp4

**Comment by maltenuhn** [comment]
@Rheeseyb I'm assigning this to you to block it - hopefully the "tunnels, not bridges" vscode replacement will make this go away entirely - but we should verify.
