### ISSUE TITLE
we have trouble importing `import splideStyle from '@splidejs/react-splide/css/core';`

### ISSUE THREAD

**Issue by balazsbajorics** [concrete-utopia/utopia#6187]
the package json has these dependencies:

```
"@splidejs/react-splide": "^0.7.12",
"@splidejs/splide-extension-auto-scroll": "^0.5.3",
```

put the line 

`import splideStyle from '@splidejs/react-splide/css/core';` anywhere in a remix route, observe the error message: 

![Image](https://github.com/user-attachments/assets/24c95844-94e1-44d7-b9d4-ed30ccc6163f)

**Comment by gbalint** [comment]
@splidejs has a module format which we don't support yet.

This is the problematic import: `import splideStyle from '@splidejs/react-splide/css/core'`

In the module resolution algorithm the module specifier is the string before the 2nd "/", so it is @splidejs/react-splide. And there is actually a package.json there, which has an exports field, which resolves the path after the module specifier (/css/core) to a file (./dist/css/splide-core.min.css)
See LOAD_PACKAGE_EXPORTS(X, DIR) in https://nodejs.org/api/modules.html#all-together

Our resolution algorithm fails to find this for multiple reasons:
- We treat the whole toImport string as the module specifier, not just the part before the 2nd slash.
- We don't parse the exports field from package.json
- We don't use the data in the exports field to resolve the returned path.

I started to write a very rough draft spike to do these, I managed to find and parse the package.json, and return the path from the exports field in package.json. It doesn't work yet, but maybe it is helpful: https://github.com/concrete-utopia/utopia/pull/6224

Let me note, that I don't think it is a good idea to quick fix the current solution, I would make sure we implement the full module resolution algorithm described in the commonjs docs.
