### ISSUE TITLE
For storyboard file, handle projects where the primary component is invoked by a `ReactDOM.render` call, but is otherwise inaccessible.

### ISSUE THREAD

**Issue by seanparsons** [concrete-utopia/utopia#630]
A common pattern in projects which are an application is the following:

```
const App = ...

ReactDOM.render(<App />, ...)
```

Ideally the use of `ReactDOM.render` should indicate a component that is more likely to be the "main" component over any other.

For those projects that have an unexported component referenced in this way, should make that be exported if possible. Otherwise perhaps add the storyboard to that file itself.

**Comment by Rheeseyb** [comment]
Definitely agree that `ReactDOM.render` should indicate the component most likely to be the main component. I think for these types of projects it would be acceptable to update their file to export that component (since that would be less intrusive than adding the storyboard to that file itself).
