### ISSUE TITLE
Navigator using stale / incorrect data after code changes

### ISSUE THREAD

**Issue by Rheeseyb** [concrete-utopia/utopia#708]
**Describe the bug**
After making a code change the Navigator frequently renders using either stale or incorrect data. Interacting with the Navigator causes it to refresh and pull in the correct data.

**To Reproduce**
This one is very easy to repro, but one example path (from a new project):

1. Insert a `View` into the root `div` of `App` (via the Canvas)
2. Select the `View` in the code editor and change it to a `div`
3. If the Navigator renders correctly, change it back via the code editor
4. Optionally type the code slowly

Result: The Navigator shows incorrect rows where the `div` should be (sometimes it still shows a `View`, sometimes an `Element`, sometimes it adds an extra row and displays the previous row as a scene, sometimes it shows just the character `d` etc.)

**Expected behaviour**
It updates correctly, showing a `div` row with the correct icon.

**Example Screen Recording**
![Navigator using stale or incorrect data](https://user-images.githubusercontent.com/1044774/99814780-5e4e7200-2b41-11eb-8a5c-870d2ce5147b.gif)

**Comment by seanparsons** [comment]
I just tried several times to reproduce this in both ways and wasn't able to.
