### ISSUE TITLE
Code selection no longer mirrors Editor (Canvas / Navigator) selection correctly

### ISSUE THREAD

**Issue by Rheeseyb** [concrete-utopia/utopia#710]
**Describe the bug**
Code selection on any element in the `App` definition will correctly update the selected element in the Editor (which will reflect in the Canvas, Navigator, and Inspector). However, for elements in other components (that also have a corresponding scene) this is not always the case

**To Reproduce**
This one appears to be related to _something_ in the Majestic Broker sample project...

1. Open https://utopia.pizza/p/6f386199-glowing-homburg/
2. CMD click to select elements in the `App` scene 
3. Now CMD click to select elements in the `Card` scene

Result: The Code Editor selection mimics the Canvas selection when selecting elements in the `App` scene, but not when selecting them in the `Card` scene. The inverse is also true when moving the cursor around in the Code Editor.

Now try the same steps in this vastly simpler (and calm-inducingly named) project: https://utopia.pizza/p/ccbc94ce-placid-rainforest/ - note that here the two are correctly linked at all times.

**Expected behaviour**
Like in the Placid Rainforest project, the Code Editor's selection should always match up to the Canvas's

**Comment by maltenuhn** [comment]
Closing since no longer applies
