### ISSUE TITLE
Editing code will often trigger a Code Editor refresh that kicks the cursor back to line 1 column 0

### ISSUE THREAD

**Issue by Rheeseyb** [concrete-utopia/utopia#731]
Often when typing code in the code editor, for some reason the cursor / carat will jump to the very beginning of the file. ~This is very easy to reproduce just by editing code.~

~Ok this is not actually easy to reproduce. Maybe I was hitting some specific usage pattern that was causing it. Will come back with repro steps when I hit it again.~

I have now found a reliable repro:

1. Create a new project
2. Open `app.js`
3. Insert a new line at the end of the imports so that you can add a new import
4. Type out `import '`

Every time when doing this after first loading the editor will trigger the bug, but trying to do it after then doesn't.

**Comment by maltenuhn** [comment]
Hmmm. I've been typing code all morning into `pizza`, and while I've noticed a bunch of things going wrong, this hasn't been one of them

**Comment by Rheeseyb** [comment]
"This is very easy to reproduce"
_Can't reproduce it again now after having it happen frequently over the last day_
I'm trying to capture a screen recording but so far nothing.

**Comment by Rheeseyb** [comment]
Updated with repro steps (finally!)

**Comment by maltenuhn** [comment]
@Rheeseyb and @balazsbajorics - I believe this is also closed, unless I mis-read what it does?

**Comment by Rheeseyb** [comment]
Yep appears to be fixed
