### ISSUE TITLE
fix Monaco local imports

### ISSUE THREAD

**Issue by balazsbajorics** [concrete-utopia/utopia#736]
https://github.com/concrete-utopia/utopia/blob/06b3eda5da965b481a0a3e565fd647226494cb5f/editor/src/components/code-editor/monaco-wrapper.tsx#L354

This seems to be incorrect as the project files are tree-shaped now.

Conversation on slack: https://paradise-engineering.slack.com/archives/C1VLFSW0H/p1605258616036300

**Comment by balazsbajorics** [comment]
I fixed this one case here, but after testing the local import autocomplete it's still almost not working and buggy, so I will keep this ticket around

**Comment by balazsbajorics** [comment]
> `monaco-wrapper.tsx` is no more. Before I close this: @balazsbajorics we still have this in `npm-dependency.tsx` - should I remove the comment? Create a new todo?
> ![image](https://user-images.githubusercontent.com/2945037/113116863-c3a82300-9205-11eb-869f-b9f8d015ed64.png)

I think it's best if you leave it as is, changing it would just destroy the context provided by git blame

**Comment by maltenuhn** [comment]
👍 . Closing this ticket.
