### ISSUE TITLE
Switching to or from the Welcome tab removes / re-adds the canvas which makes it very slow

### ISSUE THREAD

**Issue by balazsbajorics** [concrete-utopia/utopia#737]
Switching back and from from the welcome tab right now takes hundreds of milliseceonds, making a pretty lame first impression.

The welcome tab should probably be rendered on top of the canvas, obscuring it, but letting it load into the DOM while the user is reading it.

**Comment by maltenuhn** [comment]
Closing since we don't even have a welcome tab anymore, and even if we did it would be better behaved, run in an iframe prison, and only make VSCode slower.
