### ISSUE TITLE
DOM object constructor cannot be called as a function

### ISSUE THREAD

**Issue by alecmolloy** [concrete-utopia/utopia#747]
These two basic projects cause an error observed in a much more complicated project. Not sure why they cause it:

```
TypeError: Failed to construct 'Comment': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
```

- https://utopia.pizza/p/e45dccdc-charming-tibia/
- https://utopia.pizza/p/2226d6d1-shard-tugboat/

**Comment by maltenuhn** [comment]
I've just tested this; it also appears to be the case that making changes to the code does not update the canvas; see image here (note how I've renamed `Comment` to `Casdfomment` (and hit CMD+S) but the canvas error still shows `Comment`). Gratuitous splatter in the console included for your delectation.

![image](https://user-images.githubusercontent.com/2945037/100981036-84631180-3546-11eb-84d1-bde9689d0d86.png)
