### ISSUE TITLE
Fix Emotion 11.x in the canvas.

### ISSUE THREAD

**Issue by seanparsons** [concrete-utopia/utopia#765]

**Comment by seanparsons** [comment]
This appears to be working fine...

**Comment by enidemi** [comment]
1. pull in the latest @emotion/react using the dependency menu (this is the new name for emotion/core)
2. in the code editor delete jsx import from ‘utopia-api’
3. add this to the code `import {jsx} from '@emotion/react'`

Sample project
https://utopia.pizza/p/397b40de-extreme-raclette/
