### ISSUE TITLE
Preserve Comments in JSX

### ISSUE THREAD

**Issue by Rheeseyb** [concrete-utopia/utopia#795]
Follow up from #788

Preservation of comments in and around JSX (as outlined in `parser-printer-comments.spec.ts`)

**Comment by maltenuhn** [comment]
From reading `parser-printer-comments.spec.ts` I wasn't clear if this also includes comments inside of JSX attributes, e.g.
```
<div style={{
     color: 'mauve',
     // ^ ^ looks the way it sounds
    background: 'burlywood'
  }}>
```

**Comment by seanparsons** [comment]
@maltenuhn It would appear so given this list of items: https://github.com/concrete-utopia/utopia/pull/796/files?file-filters%5B%5D=.snap&file-filters%5B%5D=.ts#diff-39b9306c4d59d87d304dd47156be3ea8fab4399792c2f861354d80a602740ffcR91-R98
