### ISSUE TITLE
bundler: fix esmodules support in the module resolution

### ISSUE THREAD

**Issue by balazsbajorics** [concrete-utopia/utopia#83]
lodash-es is a special esmodules-only version (this is kind of a rarity) of lodash, and it breaks on Utopia.

The reason is that we don't yet support esmodules resolution.

I'm not sure about the size of the fix, because esmodules don't use `require()` so it will take some investigation how best to solve this for modern Chrome.

Since the number of modules that _only_ support esmodules and not the node/require style are very small (for now, but growing), I think this ticket is not urgent.

**Comment by seanparsons** [comment]
Fixed by https://github.com/concrete-utopia/utopia/pull/580
