### ISSUE TITLE
While editing code, commenting out or deleting a line of CSS causes the canvas to lose selection

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#846]
STR

1. select `div` inside app
2. navigate to the line that sets the background colour
3. _either_ press `cmd` + `/` _or_ delete the line entirely, _or_ undo one of these actions

Observed: canvas loses selection
Expected: selection remains

**Comment by Rheeseyb** [comment]
I've just tested this, and the selection is retained, but for some reason the Inspector doesn't correctly load
