### ISSUE TITLE
Remove the feature toggle for non-iframe monaco

### ISSUE THREAD

**Issue by balazsbajorics** [concrete-utopia/utopia#887]
The iframe code editor is enabled by default, but I left in the feature switch to disable it, reverting to the non-iframe version. 
The two options increase complexity and cost of maintenance of the editor, so if we all agree that the iframe version is the one true version, we should remove the other one.

**Comment by maltenuhn** [comment]
Top off my head, two considerations:
- laggy inputs without the iframe (can we verify this in a way that doesn't require on my gut feeling?)
- VSCode (and any potential perf penalties we incur)

**Comment by balazsbajorics** [comment]
> Top off my head, two considerations:
> 
> * laggy inputs without the iframe (can we verify this in a way that doesn't require on my gut feeling?)

to avoid the laggy input was the reason I made the iframe version

> * VSCode (and any potential perf penalties we incur)

I refer to @Rheeseyb  and @seanparsons

**Comment by maltenuhn** [comment]
Is there anything we're aware of about the iframe version that's a potential risk we should evaluate first, or can we take a decision now?

**Comment by balazsbajorics** [comment]
> Is there anything we're aware of about the iframe version that's a potential risk we should evaluate first, or can we take a decision now?

_oooooh_ okay I hunted down my reason for keeping the non-iframe version alive: https://github.com/concrete-utopia/utopia/pull/687#issuecomment-729876288

it turns out, I couldn't test it until it was merged and deployed, so I went ahead and just did it without waiting for approvals on the PR 

I do not remember any gotchas or known issues with the iframe version, so I think it's safe to pull the plug on the non-iframe version.
