### ISSUE TITLE
Can't select items when canvas is in preview mode

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#916]
**Describe the bug**
We used to be able to select items on the canvas when the canvas was in preview mode, using `cmd`. This still works for scenes, but no longer for elements.

**To Reproduce**

1. Insert div with content into a new project
2. Enter canvas preview mode
3. hold down `cmd` and hover over the div

Result: It doesn't highlight, it doesn't get selected on click

**Expected behaviour**
It highlights and gets selected on click, while holding down cmd only

**Comment by maltenuhn** [comment]
@balazsbajorics might this have regressed when we moved to the non-computed targeting?

**Comment by balazsbajorics** [comment]
> @balazsbajorics might this have regressed when we moved to the non-computed targeting?

yep, it is very likely that I broke this!

**Comment by maltenuhn** [comment]
Closed by #949
