### ISSUE TITLE
Selection is always lost after any model change

### ISSUE THREAD

**Issue by Rheeseyb** [concrete-utopia/utopia#940]
Believed to be caused by UIDs now being a hash of the code

**Comment by maltenuhn** [comment]
@seanparsons already left this comment in the Canvas doc a month ago:

> ​​Yeah, as it’s starting from a file with no data-uid​ properties in there it attempts to generate them from a hash of the representation. But if the currently selected item changes because the code changes, the hash will change as well which means it gets a new data-uid​ key.
