### ISSUE TITLE
Canvas doesn't keep up with code changes

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#947]
Infrequently the canvas does not seem to get the 'latest' code, anecdotally when pausing and then continuing typing, or typing fast.

To replicate, create this new component by typing it out by hand per the screenshot one-liner. Note how the canvas complains about an unterminated regex, and has the incomplete (a-few-keystrokes-behind) code showing

![image](https://user-images.githubusercontent.com/2945037/109652417-ac6b0c80-7b57-11eb-9275-8c79125a2e18.png)

**Comment by maltenuhn** [comment]
@balazsbajorics and @Rheeseyb - also done  _I think_ ?

**Comment by Rheeseyb** [comment]
Yep done
