### ISSUE TITLE
[Bug] VS Code believes version on disk is newer than currently open file when reloading whilst developing Utopia

### ISSUE THREAD

**Issue by Rheeseyb** [concrete-utopia/utopia#970]
To repro:

1 - Start editing a project without saving
2 - Make a change to Utopia's code that triggers a reload
3 - You should receive an error from VS Code stating that the version on disk is newer

**Comment by maltenuhn** [comment]
@seanparsons  a freebie / duplicate from #1041 closed by #1107 ?

**Comment by seanparsons** [comment]
@maltenuhn Looks a lot like it.

**Comment by Rheeseyb** [comment]
Closed by #1107
