### ISSUE TITLE
Remove `Positionable` etc utopia-API wrappers, and other places in our codebase that use / rely on them

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#996]
**Problem** `Positionable` was a concept introduced in the olden days, to circumvent the problem of immovable / non-style-or-classname-supporting 3pty components. However, it hasn't worked in a while, is inaccessible, and in the New World _full of_ vanilla React code and 3pty imports, it no longer is an acceptable work-around. Ergo, we should remove it

**Solution**

Terminate with prejudice, including its `utopia-api` alter-ego, any wrapping actions that make use of it, and whatever tests we had that tested this.

**Comment by maltenuhn** [comment]
@enidemi wasn't this something you were tackling as part of another ticket? Free bonus points 😁

**Comment by enidemi** [comment]
yes as part of https://github.com/concrete-utopia/utopia/issues/1156 I'm gonna remove the unused layout components too
